- pkg/oras/oras_test.go
Test fails on Windows due to Unix/Linux file delimiters.
> Fix test failure on Windows

- README.md
- cmd/oras/pull.go
- cmd/oras/push.go
- examples/simple_push_pull.go
- pkg/content/consts.go
- pkg/content/errors.go
- pkg/content/file.go
- pkg/content/memory.go
- pkg/content/readerat.go
- pkg/content/utils.go
- pkg/oras/consts.go
- pkg/oras/errors.go
- pkg/oras/oras_test.go
- pkg/oras/pull.go
- pkg/oras/push.go
- pkg/oras/store.go
Introducing `MemoryStore` and `FileStore` to provide and ingester contents.
All intermediate files are stored in the memory, and other files can be fetched from any `content.Provider` or be stored in any `content.Ingester`.
fix #20
> push to / pull from content store

- cmd/oras/pull.go
- pkg/content/content_test.go
- pkg/content/file.go
It makes more sense to overwrite by default when pulling at the `tar` tool does.
> Overwrite by default when pulling

- cmd/oras/push.go
- pkg/oras/push.go
- pkg/oras/push_opts.go
Support customized manifest config by the `--manifest-config file[:type]` option. Similar to the file reference, it is possible to change the media type of the manifest config.
Support customized annotations for the manifest, the config, and individual layers by the `--manifest-annotations file` option. The annotations file is a JSON file with the following format:
```json
{
"<filename>": {
"<annotation_key>": "annotation_value"
}
}
```
There are two special filenames / entries:
- `$config` is reserved for the annotation of the manifest config.
- `$manifest` is reserved for the annotation of the manifest itself.
For instance, the following annotation file
```json
{
"$config": {
"hello": "world"
},
"$manifest": {
"foo": "bar"
},
"cake.txt": {
"fun": "more cream"
}
}
```
results in
```json …
```
> Customized Config and Annotations Support

- Gopkg.lock
- cmd/oras/login.go
- cmd/oras/logout.go
- cmd/oras/main.go
- cmd/oras/pull.go
- cmd/oras/push.go
- cmd/oras/resolver.go
- pkg/auth/client.go
- pkg/auth/docker/client.go
- pkg/auth/docker/login.go
- pkg/auth/docker/logout.go
- pkg/auth/docker/resolver.go
This PR supports
- `oras login` to log in to a remote registry.
- `oras logout` to log out from a remote registry.
It re-uses the auth config from docker cli, so as docker credential helpers. By default, it uses the default docker config and it can be overridden by setting the `--config` option. Multiple config files can be taken that if the credential is not found in the first config, `oras` continue to search from the next config file.
For login and logout, the credential changes always occur in the first config file (i.e. all config files except the first one are read-only).
@sajayantony @jdolitsky This is a supportive solution to https://github.com/helm/helm/issues/5461
> Support oras login

- README.md
This shows an example of how to run a docker registry with a username/password combo for testing
> Add readme on login/logout

- cmd/oras/pull.go
- cmd/oras/push.go
- pkg/content/consts.go
- pkg/content/file.go
- pkg/content/utils.go
This PR enables `oras` to push / pull a directory to / from a remote registry.
To push, the target directory is compressed into a `tar.gz` temproray file (on Linux, it sits at `/tmp`). Then the `tar.gz` file is pushed normally with media type `application/vnd.oci.image.layer.v1.tar+gzip` and extra annotations
- `io.deis.oras.content.digest`: the `sha256` digest of the internal `tar` file. It is different from the digest of the `tar.gz` file.
- `io.deis.oras.content.unpack`: marked as `true` for extration when pull.
To pull, the `tar.gz` file is pulled to a temprorary directory. Then it is extracted and verified against `io.deis.oras.content.digest`.
Notes:
- Since the temp files are introduced, please call `defer store.Close()` for `*FileStore` to release resources.
- The pushed directory …
> Directory Support

- cmd/oras/push.go
- cmd/oras/push_unix.go
- cmd/oras/push_windows.go
Better cross-platform support on Windows.
With this patch,
- Windows path are automatically converted to "/" except absolute paths. For instances,
- `foo\bar\hello.txt` --> `foo/bar/hello.txt`
- `C:\hello.txt` --> `C:\hello.txt` (no change)
- Allow file reference with Windows absolute paths. For instance,
- `C:\hello.txt`
- `C:\hello.txt:vnd.your.media.type`
Fixes #62, #63
> Cross-platform support on path

- Gopkg.lock
- pkg/auth/client.go
- pkg/auth/docker/client_test.go
- pkg/auth/docker/logout.go
`Logout` returns `ErrNotLoggedIn` if a registry is not logged in.
If the multiple config paths are used, the check will verify the login record against all configs. However, it only logs out from the primary config setting since the backup configs are supposed to be read-only.
Resovles #71
> Logout returns error if not logged in

- cmd/oras/pull.go
- cmd/oras/push.go
- pkg/context/context.go
- pkg/context/logger.go
Discard logger by default unless `--debug` is toggled.
@jdolitsky Take a look at `pkg/context/logger.go`. You may need `WithLoggerFromWriter()` or `WithLoggerDiscarded()` for helm 3.
Resolves #72
> Discard logger

- pkg/oras/errors.go
- pkg/oras/oras_test.go
- pkg/oras/pull.go
- pkg/oras/pull_opts.go
- pkg/oras/push.go
- pkg/oras/push_opts.go
The caller can opt to pull contents in sequence with breath-first search. For example,
```go
oras.Pull(ctx, resolver, ref, store, oras.WithPullByBFS)
```
Combining with the `oras.WithPullBaseHandler` option, the caller is able to conditional pulling. Here is the example code.
```go
oras.Pull(ctx, resolver, ref, store, oras.WithPullByBFS,
oras.WithPullBaseHandler(images.HandlerFunc(func(ctx context.Context, desc ocispec.Descriptor) ([]ocispec.Descriptor, error) {
if !shouldContinue(ctx, desc) {
// the blob of the current descriptor is not pulled
return nil, oras.ErrStopProcessing
}
return nil, nil
})))
```
Details see `oras_test.go`.
Resolves #75 
Resolves #76
> Allow sequential pulling with break in the middle

- cmd/oras/pull.go
- cmd/oras/push.go
- pkg/oras/pull.go
- pkg/oras/pull_opts.go
Enhance user experience on Push and Pull. Resolves #77.
```
$ oras push localhost:5000/club:party cake.txt juice.txt
Uploading be6fe1187628 juice.txt
Uploading 22af0898315a cake.txt
Pushed localhost:5000/club:party
Digest: sha256:5c46f904baecbd34f1a261e67200faed4bb0a904d152af3cdd7c9a57ac017998
$ oras pull localhost:5000/club:party
Downloaded be6fe1187628 juice.txt
Downloaded 22af0898315a cake.txt
Pulled localhost:5000/club:party
Digest: sha256:5c46f904baecbd34f1a261e67200faed4bb0a904d152af3cdd7c9a57ac017998
```
With verbose:
```
$ oras push -v localhost:5000/club:party cake.txt juice.txt
Preparing cake.txt
Preparing juice.txt
Uploading be6fe1187628 juice.txt
Uploading 22af0898315a cake.txt
Pushed localhost:5000/club:party
Digest: …
```
> Better UX on Push / Pull

- cmd/oras/pull.go
Resolves #78 
Example output:
```
$ oras pull localhost:5000/just_name
Error: image reference format is invalid. Please specify <name:tag|name@digest>
```
> Human friendly errror output

- pkg/content/consts.go
- pkg/content/errors.go
- pkg/content/file.go
- pkg/content/interface.go
- pkg/content/oci.go
- pkg/oras/pull.go
- pkg/oras/pull_opts.go
Resolves #107 
Example usage:
```go
func demo() error {
ref := "localhost:5000/oras:test"
ctx := context.Background()
resolver := docker.NewResolver(docker.ResolverOptions{})
store, err := content.NewOCIStore("store")
if err != nil {
return err
}
desc, _, err := oras.Pull(ctx, resolver, ref, nil,
oras.WithContentProvideIngester(store),
oras.WithPullEmptyNameAllowed(),
)
if err != nil {
return err
}
store.AddReference(ref, desc)
return store.SaveIndex()
}
```
It stores pulled content in the `store` folder as
```
store
├── blobs
│   └── sha256
│       ├── 03ba204e50d126e4674c005e04d82e84c21366780af1f43bd54a37816b6ab340
│       ├── 130c6b42d2ea0bbf0cc727aa2c2c193d1550e84b62202efbc1f24b5adddebd30
│       └── 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
├── index.json
├── …
```
> New OCIStore

- cmd/oras/login.go
- pkg/auth/client.go
- pkg/auth/docker/client_test.go
- pkg/auth/docker/login.go
Implement issue https://github.com/deislabs/oras/issues/109.
Add `--insecure` flag when login registry, it can allow connect the registry without certs.
Example: `oras login --insecure registry.com`
> Add insecure flag when login registry

- README.md
Resolves https://github.com/deislabs/oras/issues/112 .
> Add --insecure flag usage document in readme

- pkg/artifact/consts.go
- pkg/oras/push.go
This addressed the config part of #115 
This PR fixes the default config media type as shown below 
```
{
"schemaVersion": 2,
"config": {
"mediaType": "application/vnd.unknown.config.v1+json",
"digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
"size": 2
},
"layers": [
{
"mediaType": "application/vnd.oci.image.layer.v1.tar",
"digest": "sha256:25748995a84fc5a1e85b53cd07dffc6e50e2cab1c34a49d9969f0f070d48468f",
"size": 12912560,
"annotations": {
"org.opencontainers.image.title": "oras"
}
}
]
}
```
> Added unknown config mediaType

- README.md
However it seems to require the `--manifest-config` option on pull, with
at least an empty JSON object set; the default does not currently work.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>
> Docker Hub now supports OCI images

- pkg/oras/push.go
- pkg/oras/push_opts.go
**What this does**
This PR adds a new field to `PushOpt`, and corresponding config functions, to allow giving an entire manifest descriptor to ORAS when pushing.
**Why**
I've been experimenting with building small, static images using ORAS, while still making them appear as standard docker v2-2 images rather than OCI. 
I found that I could do almost everything I needed to aside from overriding the ManifestDescriptor - which I needed to do to set the MediaType on the manifest (`image-spec` omits this field, but docker registry complains about it).
See where I'm using this here: https://github.com/ecordell/bndlr/blob/master/pkg/bundle/bundle.go#L58-L79
Also open to feedback and suggestions if there are better approaches to what I'm doing. Thanks!
> Allow overriding the ManifestDescriptor when pushing

- cmd/oras/pull.go
- cmd/oras/push.go
- cmd/oras/resolver.go
- implementors.md
- pkg/auth/client.go
- pkg/auth/docker/resolver.go
This is the first commit about pull/push to an insecure registry.  
This PR implement pull or push to an insecure registry using the CNAME, but using the ip address is wrong. So this PR setting WIP. 
If someone know why, please tell me, thanks.
TODO:
Related issue:
- https://github.com/helm/helm/issues/6324
> Add insecure and plain-http flag when pull and push

- BUILDING.md
- Makefile
> Enable ARM64 linux builds.

- cmd/oras/pull.go
- cmd/oras/push.go
- pkg/oras/errors.go
- pkg/oras/oras_test.go
- pkg/oras/push.go
Allow oras to push or pull empty artifact, which has no layers but a config.
CLI experience is shown as follows.
- on push:
```
PS C:\> oras push shizhtest.azurecr.io/oras/empty:latest
Uploading empty artifact
Pushed shizhtest.azurecr.io/oras/empty:latest
Digest: sha256:bc4b23b58840b73e24d7be3ff6baa477a830999023af4c75c83ec4db6c86fc9a
```
- on pull:
```
PS C:\> oras pull shizhtest.azurecr.io/oras/empty:latest
Downloaded empty artifact
Pulled shizhtest.azurecr.io/oras/empty:latest
Digest: sha256:bc4b23b58840b73e24d7be3ff6baa477a830999023af4c75c83ec4db6c86fc9a
```
Resolves #153
> Allow empty artifact

- BUILDING.md
Documentation changes for #100
> update BUILDING doc for Go dependencies

- pkg/auth/docker/client.go
As title.
For better code. Before `for`-looping, IMO, it is better to check the length and early return if the length is zero.
> Refactor docker/NewClient to use early return

- implementors.md
Adds a reference to GAR support.
Closes #157
> docs: add GAR

- pkg/content/iowriter.go
- pkg/content/passthrough.go
- pkg/content/passthrough_test.go
As discussed with @SteveLasker , this is the first of 2-3 PRs expanding the capabilities of the `store` package.
There are two additions here:
* `PassthroughWriter` that lets you wrap any other underlying store (e.g. file, memory) and have a processor function in the middle. Thus if I wanted to decrypt the content in transit, or uncompress, or any other action, I have a simple framework for doing so.
* `IoWriter` is very similar to `FileStore`, except instead of taking a directory and opening files, it takes an actual `io.Writer` and passes it through. I have used it to, e.g. write directly to block devices, and to write to another stream over a network. It is more fine-grained control as you can pass it any `io.Writer` you want.
Once these are in, I have two more that take advantage of …
> create pass-through writer and iowriter

- .github/dependabot.yml
Signed-off-by: Jinesi Yelizati <i63888888@163.com>
With this PR, [Dependabot](https://dependabot.com/) can automatically/daily scan the dependencies described in `go.mod` and create a pull request if there is a newer version of the upstream package available.
The maintainers of this repository don't need to check the versions of the upstream packages manually. They can simply merge the PR if the tests in CI passed.
How Dependabot works:
- Dependabot checks for updates
- Dependabot opens pull requests
- You review and merge
You can check my forked repository https://github.com/ylz-at/oras/pulls to see what kind of PRs does Dependabot create.
And in `ylz-at/oras` there are already 5 PRs automatically created by Dependabot.
**Special notes for your …
> chore(deps): add dependabot.yml

- pkg/content/consts.go
- pkg/content/gunzip.go
- pkg/content/untar.go
This leverages the `PassthroughWriter` to create gunzip and untar writers.
These can be chained. I use it as follows (skipping error handling):
```go
writer, err := ingester.Writer(ctx, opts...)
// figure out which writer we need
hasGzip, hasTar := checkCompression(desc.MediaType)
if hasTar {
writer = NewUntarWriter(writer, d.blocksize)
}
if hasGzip {
writer = NewGunzipWriter(writer, d.blocksize)
}
// `writer` now will process the stream through gunzip and then through untar before passing it on to the original ingester writer
```
I actually have all of the above wrapped up in a `DecompressStore` which I pass to `oras.Pull`.
> gunzip and untar passthrough writers

- pkg/content/consts.go
- pkg/content/gunzip.go
- pkg/content/iowriter.go
- pkg/content/opts.go
- pkg/content/passthrough.go
- pkg/content/passthrough_test.go
- pkg/content/untar.go
In most cases, e.g. a remote OCI registry store, you want to hash the retrieved object and validate it. But sometimes you don't, e.g. if you truly trust the store, or if the trade-off in hashing cost is too high. This gives you the option to skip hashing.
> options for content.Writers; options to pre-provide input and output hashing, and blocksize

- pkg/content/opts.go
Although we do have a default, in theory, but if someone actually calls: `WithBlocksize(0)`, it will override the default, and break all sorts of things. This adds a safety check.
> prevent anyone from accidentally setting the blocksize to zero

- pkg/content/decompressstore.go
- pkg/content/decompressstore_test.go
The doc describes it. If I pass `FileStore` to `oras.Pull` as the `ingester`, then it just takes the artifact in whatever format it is. That is fine in some use cases. In others, I might have the artifact compressed with gzip, or wrapped in a single tar file. This is most common when using a registry that doesn't have proper artifact support, so every artifact is just tarred and gzipped and given the legacy media-type. It also is common with compressing artifacts, using just gzip.
This creates an optional "wrapper" store, so you can do:
```go
fileStore := content.NewFileStore(path)
decompressStore := NewDecompressStore(fileStore)
oras.Pull(... decompressStore ...)
```
This leverages the `UntarWriter` and `GunzipWriter` from earlier commits.
I think the options to `DecompressStore` could …
> add optional decompressstore

- pkg/content/multireader.go
- pkg/content/multireader_test.go
Provides option to wrap multiple stores to get a single `content.Provider` that can be used anywhere a `Provider` is needed.
> add multireader

- cmd/oras/cache.go
- cmd/oras/pull.go
- go.mod
- go.sum
Resolves #193. The cache is enabled only when the environment variable `ORAS_CACHE` is set in the CLI.
Example usage:
```bash
export ORAS_CACHE=~/.oras/cache
oras pull localhost:5000/hello:latest
```
> oras pull with cache

- pkg/auth/docker/client_test.go
Fix build failure due to errors in `pkg/auth/docker/client_test.go`. The root cause is that the test registry may not be running before any test cases.
> Fix `pkg/auth/docker` test

- pkg/content/decompressstore.go
- pkg/content/decompressstore_test.go
- pkg/content/multiwriter.go
- pkg/content/opts.go
- pkg/content/passthrough.go
- pkg/content/untar.go
This is a first cut attempt at this. It needs proper tests, which I am willing to add once we have agreement on the idea.
@jdolitsky this is what we discussed over Slack.
The [DecompressStore](https://github.com/deislabs/oras/blob/0bffdbc8b717fdf774259c96f7ac285089f8ceaa/pkg/content/decompressstore.go#L22) has support for determining that a particular blob is tarred and then untarring it. This is great, but it assumes that the tar contains only one file. It even [ignores the filename](https://github.com/deislabs/oras/blob/0bffdbc8b717fdf774259c96f7ac285089f8ceaa/pkg/content/untar.go#L30-L35):
```go
_, err := tr.Next()
if err == io.EOF {
// clear the error, since we do not pass an io.EOF
err = nil
break // End of archive
}
```
One could argue about whether we should or should not support …
> multiwriteringester support

- pkg/content/oci.go
Update descriptor in the nameMap as well as in index.Manifests.
nameMap used in the ListReferences operation and should return actual descriptor.
> Fix OCIStore inconsistent state after AddReference

- go.mod
Because `replace` directive is ignored when this is used as a library import.
> actual versions in go.mod

- pkg/content/multiwriter.go
- pkg/content/passthrough.go
- pkg/content/passthrough_test.go
- pkg/content/untar.go
The multiwriter passed a `map[string]content.Writer`. The problem is that the thing that creates these writers sometimes doesn't know what writer it will use until later. This changes it to a func, so that it can determine it on the fly. The net result is the same, with some more flexibility.
Discussed on slack with @jdolitsky 
I still have some work to do to be sure this is ready, but the initial view can get looked at.
> use function instead of static map

- pkg/content/decompressstore.go
- pkg/content/decompressstore_test.go
I should have done this from the beginning. The decompress store treats `+gzip` as gzip and `.tar` as tar. This is correct, but there still its plenty out there that uses `.gzip`
This just handles that equally sanely. Adds it to the test as well, because we are well-behaved citizens. 😄
> handle different gzip extensions

- pkg/content/file.go
- pkg/content/file_test.go
- pkg/content/opts.go
When we try to write to a FileStore (or more accurately, create a Writer from a FileStore), using a Descriptor that doesn't have a title annotation - `ocispec.AnnotationTitle` - then FileStore returns an `ErrNoName`.
This adds an option to ignore that error, i.e. if you pass it a descriptor without a name, `FileStore` will just ignore it, writing it to `ioutil.Discard`. This option allows one to blindly pass an entire OCI manifest and all of its dependencies to FileStore, which only will write down the ones it knows how to handle.
The default, of course, remains unchanged.
Also added a basic test.
As discussed with @jdolitsky in #230
> filestore option to ignore noname error

- pkg/oras/oras_test.go
- pkg/oras/store.go
Fixes #225 
This does not change what gets cached or not - expect a separate PR on that - but it has the cache be write-through.
Current behaviour: if the item is to be cached, cache it; if not, pass it through to the underlying store. This means the underlying store doesn't even have the opportunity to decide if it wants to do anything with the cached data. It is to cache or to underlying store, but not both.
PR behaviour: if the item is to be cached, cache it *and* pass it through to the underlying store; if not, *just* pass it through to the underlying store. The cache becomes a write-through cache.
Of course, the underlying store still might decide to reject or discard.
> pass through on write

- pkg/oras/pull.go
- pkg/oras/pull_opts.go
- pkg/oras/push.go
- pkg/oras/store.go
Fixes #226 
But worth awaiting the result of #225 before merging in to see any impact.
> cache docker types too

- implementors.md
👋🏻 Hi from GitHub! We'd like to add our [Container Registry](https://docs.github.com/en/packages/guides/about-github-container-registry) implementation to your implementors guide.
Please let me know if there is anything else needed!
> Add GitHub Container Registry Implementor

- .goreleaser.yml
- BUILDING.md
- Makefile
This PR adds arm64 binaries for linux and darwin (Apple Silicon) to the release pipeline. Darwin arm64 is [supported as of golang 1.16](https://golang.org/doc/go1.16#darwin). Windows arm64, however, is not yet supported.
Additionally this updates a couple typos in the build docs.
> Build & release arm64 binaries

- .github/workflows/build-pr.yml
- .github/workflows/build.yml
- Makefile
- examples/simple_push_pull.go
- pkg/content/content_test.go
- pkg/content/file.go
- pkg/content/file_test.go
- pkg/content/opts.go
- pkg/oras/oras_test.go
- scripts/acceptance.sh
Change the default for writer opt 'IgnoreNoName' to be true. This was set to false, and causing the example to not run properly.
A new option 'WithErrorOnNoName' has been added to be used in cases when this behaviour is expected. The existing option 'WithIgnoreNoName' has now been deprecated.
A simple bash-based acceptance test has been added to prevent this issue in the future. This starts a registry, compiles the example into a binary, and makes sure it runs properly. This test is now run in CI.
Fixes #246
Alternative to #247 and #249
> Fix regression in v0.11.0

- README.md
There are a few broken links to a previously existing implementors.md, and they should now link to the web-rendered docs. This will close #269.
And a naive question - if I want to implement a registry with custom artifact types, if oras serves as the client, is there a matching oci registry server in go that I can tweak to have custom artifacts/behavior, tweak the interface, etc.? I've never made a webby thing with go and thought it would be fun.
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
> fixing broken links in readme

- cmd/oras/pull.go
Add a new option named `--manifest-config` to `oras pull` so that `oras` can pull the config file as well even if the config is not named. Like `oras push`, file name with media type should be passed to the `--manifest-config` option. The media type is optional and its default value is `application/vnd.unknown.config.v1+json`. The resulted config will be written to the specified file name.
Examples:
```
$ oras pull --manifest-config config.json localhost:5000/hello:latest
Downloaded a948904f2f0f hi.txt
Downloaded 57f840b6073c config.json
Pulled localhost:5000/hello:latest
Digest: sha256:a5d8f401e10aa320bd7ecabbfbabb89b0e59e599c9fdc6587edbffaf232fa4f3
```
```
$ oras pull --manifest-config config.json:application/vnd.unknown.config.v1+json localhost:5000/hello:latest
Downloaded a948904f2f0f …
```
> Enable CLI to Pull Config

- cmd/oras/cache.go
- cmd/oras/discover.go
- cmd/oras/push.go
- go.mod
- go.sum
- internal/resolver/dummy.go
- pkg/oras/discover.go
- pkg/oras/pull.go
- pkg/oras/pull_opts.go
- pkg/oras/push.go
- pkg/oras/push_opts.go
> Updated oras to use updated containerd with artifacts-spec v1

- cmd/oras/discover.go
- go.mod
- go.sum
Before:
```
$ oras discover --plain-http --output tree $reg/test:base
localhost:5000/test:base
├── [foo]sha256:3c6ed9d37e825a80565d2e9602d727cd076ed7c5bf15c9193f6df6248735828c
├── [foo]sha256:4cbfbbe2e37038d8b6bffe99622c92709d9703e95f85851fc08953de176951a1
└── [bar]sha256:ccb9446f7dc9a55448c7f17dea6eda2c74ceda1c021dc747737c6f7b05584b0f
```
After:
```
$ oras discover --plain-http --output tree $reg/test:base
localhost:5000/test:base
├── foo
│   ├── sha256:3c6ed9d37e825a80565d2e9602d727cd076ed7c5bf15c9193f6df6248735828c
│   └── sha256:4cbfbbe2e37038d8b6bffe99622c92709d9703e95f85851fc08953de176951a1
└── bar
└── sha256:ccb9446f7dc9a55448c7f17dea6eda2c74ceda1c021dc747737c6f7b05584b0f
```
> Pretty Print Tree in ORAS Discover

- pkg/auth/docker/resolver.go
This fixes the `oras discover` on auth credentials from config files.
> Add headers to docker resolver

- cmd/oras/resolver.go
This PR unifies the authentication experience in oras.
Previously, we need to specify username and password for discover related scenarions as oras does not honor the login credentials by `oras login`.
> Unify authentication

- cmd/oras/login.go
- internal/http/certificate.go
- internal/http/client.go
- internal/http/client_test.go
This PR enables configuring certificate authority files for registry client.
For now this was only used in `login` command but will also be applied to `pull` and `push` commands after revamping.
#217
> Support certificate authority configuration

- cmd/oras/pull.go
This PR removes two media type options and artifact will be pull with the stored media type.
Resolves #130
> Remove media type options for pull operation

- go.mod
- go.sum
This PR upgrades the underlying oras-go to v2.0.0-alpha
> Upgrades to oras-go v2.0.0-alpha

- .github/workflows/release-ghcr.yml
- .github/workflows/release-github.yml
This PR rewrites give least privildege access to releasing github actions:
- For binary release, the action need to read source code and write to release contents
- For container image release, the action need to read source code and write to ghcr packages
Resolves #427
> Update ghcr package action yaml

- cmd/oras/pull.go
Resolves https://github.com/oras-project/oras/issues/434
> fix: update help msg description about pullCmd()

- cmd/oras/push.go
Resolve part of #466 
Signed-off-by: Haoliang Yue <yuehaoliang@microsoft.com>
> feat: use --artifact-type to change the media type of the config blob

- Makefile
This PR adds changes to support ORAS CLI on windows 64 Architecture.
Signed-off-by: Koushik Dey <57134947+koushdey@users.noreply.github.com>
> Adding support for windows-arm64

- cmd/oras/copy.go
> fix(lang): update misspelling in copy.go

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/release-github.yml
- Dockerfile
- go.mod
Fixes #478 
Test build and release can be found here - 
[Bump to golang 1.19](https://github.com/sajayantony/oras/actions/runs/2836036330)
release-ghcr #10: Commit [3d7c282](https://github.com/sajayantony/oras/commit/3d7c28231864c608ae2680a1a43b2c17b3dba11a) pushed by [sajayantony](https://github.com/sajayantony)
[v2.0.0-alpha-go1.9](https://github.com/sajayantony/oras/tree/v2.0.0-alpha-go1.9)	
4 minutes ago
3m 25s
[Bump to golang 1.19](https://github.com/sajayantony/oras/actions/runs/2836036328)
release-github #10: Commit [3d7c282](https://github.com/sajayantony/oras/commit/3d7c28231864c608ae2680a1a43b2c17b3dba11a) pushed by [sajayantony](https://github.com/sajayantony)
[v2.0.0-alpha-go1.9](https://github.com/sajayantony/oras/tree/v2.0.0- …
> Bump to golang 1.19

- cmd/oras/pull.go
- internal/docker/mediatype.go
#274 enables the CLI to pull manifest config. However, the user must provide the desired media type of the config or use the default. This PR allows pulling arbitrary manifest config.
If the user does not specify the desired media type, the code will get the 0th indexed node as the manifest config if its parent node is a manifest.
Note: For a manifest, the 0th indexed element is always a manifest config. ref: https://github.com/oras-project/oras-go/blob/6a09a65fcc0b96c3448e988c1727ed154c2388ea/content/graph.go#L58
Examples:
```
$ oras pull --manifest-config config.json localhost:5000/hello:latest
Downloaded  3ad08644ab5a artifact.txt
Downloaded  98df5c495df6 config.json
Pulled localhost:5000/hello:latest
Digest: sha256:8627dfe823698a566e105d961045eafcaa9115b6faf1f625edd85df558421bd5
``` …
> feat: Support pulling arbitrary manifest config

- cmd/oras/manifest/fetch.go
So linux prompt will not be shown right after the prettified result.
> fix: add new line to prettify manifest fetch result 

- cmd/oras/manifest/fetch.go
Improve error message on platform mismatch
Resolves: https://github.com/oras-project/oras/issues/498
> refactor: improve error message on platform mismatch

- cmd/oras/internal/option/remote.go
- cmd/oras/logout.go
- cmd/oras/pull.go
- Rename current `-c/--config` option to `--registry-config`
- Rename `--manifest-config` to `--config`
Resolves: https://github.com/oras-project/oras/issues/495
> refactor!: rename the --manifest-config to --config

- cmd/oras/internal/option/remote.go
This bug was introduced in PR https://github.com/oras-project/oras/pull/432.
`fs.Lookup("config") != nil` was intended to check whether there was an existing config to avoid repeatedly setting the config value. However, we are not able to set the config value if `fs.Lookup("config")` returns nil.
This PR changed the check to `if fs.Lookup("config") == nil {}`
> fix: fix the lookup check for registry-config option

- cmd/oras/attach.go
- cmd/oras/internal/option/packer.go
- cmd/oras/push.go
Defined pre-defined annotation keys in `option.Packer`, and replaced other const defined with the same value.
Updated annotation related example description.
> refactor: add pre-defined annotation keys into option.Packer

- cmd/oras/internal/display/print.go
This PR cleans up duplicated code for status printing
> refactor: reuse print status func

- cmd/oras/pull.go
Note that there are comments in line 115-119.
This pr adds additional comments before and inside the loop of successors to describe what the loop does.
Part of issue #415 
> docs: add doc comments for the loop of successors

- cmd/oras/pull.go
This pr adds empty string check before writing configPath to Annotations, so that if a config only specifies the type but not name, oras cli should not fetch the content of this config.
Part of issue #415 
> fix: check if configPath is empty before writing to Annotations

- cmd/oras/pull.go
Print digest and media type when content is skipped, and use sync.Map to ensure skipped content is printed only once.
Part of issue #415 
> feat: print digest and media type when content is skipped using sync.Map

- cmd/oras/internal/display/print.go
- cmd/oras/pull.go
The verbose flag should work properly when unnamed content is skipped or downloaded. It currently does not. Example: this "downloading" is not paired with a "downloaded".
Part of issue #415 
> fix: print post-copy logs for unnamed content in verbose mode

- cmd/oras/main.go
- cmd/oras/tag/tag.go
Resolve #471 
Signed-off-by: Jun <wju@microsoft.com>
> feat: enable tagging manifests

- cmd/oras/manifest/fetch.go
- go.mod
- go.sum
Bump oras-go from rc2 to latest code
Remove error message on platform mismatch in fetch.go since https://github.com/oras-project/oras-go/pull/292 has already improve error message on platform mismatch in order to distinguish platform not found and manifest not found.
> chore: upgrade oras-go

- cmd/oras/internal/option/descriptor.go
- cmd/oras/internal/option/descriptor_test.go
- cmd/oras/internal/option/pretty.go
- cmd/oras/internal/option/pretty_test.go
Add Descriptor and Pretty options for ORAS command so that these options could be used later in push/fetch/delete commands.
> feat: add Descriptor and Pretty options for ORAS command

- cmd/oras/pull.go
- internal/cache/target.go
- internal/cache/target_test.go
- internal/cas/fetch.go
Use `oras.ReadOnlyTarget` instead of `oras.Target` for the target storage with caching
> refactor: use read only target to replace oras.Target for the target storage with caching

- .github/.codecov.yml
- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/release-ghcr.yml
- .github/workflows/release-github.yml
- .gitignore
- .goreleaser.yml
- Dockerfile
- Makefile
- cmd/oras/main.go
- cmd/oras/version.go
- internal/credential/store.go
- internal/version/version.go
This PR will fix the missing license headers mentioned in #435 using the [skywalking-eyes](https://github.com/apache/skywalking-eyes) `fix header` tool.
Header check result is shown as follows:
```
INFO Loading configuration from file: .licenserc.yaml
INFO Totally checked 730 files, valid: 38, invalid: 14, ignored: 678, fixed: 0
INFO GITHUB_TOKEN is not set, license-eye won't comment on the pull request
ERROR the following files don't have a valid license header:
.github/.codecov.yml
.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/release-ghcr.yml
.github/workflows/release-github.yml
.gitignore
.goreleaser.yml
Dockerfile
Makefile
cmd/oras/main.go
cmd/oras/version.go
internal/credential/store.go
internal/version/version.go
ERROR …
```
> fix: add missing license headers

- go.mod
- go.sum
Upgrade oras-go to v2.0.0-rc.3
> chore: upgrade oras-go to v2.0.0-rc.3

- cmd/oras/blob/fetch.go
Add `oras blob get` alias for `oras blob fetch` command
Resolves: https://github.com/oras-project/oras/issues/550
> fix: add get alias for oras blob fetch command

- cmd/oras/blob/fetch.go
- go.mod
- go.sum
> fix: use VerifyReader to verify read content after oras.Fetch

- cmd/oras/manifest/delete.go
- cmd/oras/manifest/push.go
- cmd/oras/tag/tag.go
> doc: fix description typos

- cmd/oras/blob/push.go
From:
to:
Resolves: https://github.com/oras-project/oras/issues/613
> fix: fix flag name parsing error for oras blob push

- cmd/oras/pull.go
- cmd/oras/push.go
resolves: #620 
Signed-off-by: Jun <wju@microsoft.com>
> feat: add concurrency flag for oras pull

- cmd/oras/tag/tag.go
> fix: capitalize the short and log doc for tag command

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/license-checker.yml
- cmd/oras/manifest/fetch.go
I have validated it in my own repo: [build](https://github.com/qweeah/oras/actions/runs/3225144165)
Resolves #640 
> ci: run all check CIs against patch PR

- .github/workflows/release-github.yml
- Dockerfile
This PR bumps golang version used by go releaser and buildx.
Resolves: #647
> bump: upgrade golang to 1.19.2

- cmd/oras/attach.go
- cmd/oras/push.go
- go.mod
- go.sum
Since oras-go will take care of fallback with tag schema if referrer API not supported, this PR provides OCI Image fallback when-and-only-when OCI artifact is not supported.
Resolves: #654
> feat!: support OCI image fallback for `oras push` and `oras attach`

- cmd/oras/repository/show-tags.go
Making this PR draft since I found that it's important to write good example and long description for the new flag.
Resolves #658
> feat: support excluding digest tags

- cmd/oras/cp.go
- cmd/oras/repository/cmd.go
- cmd/oras/repository/ls.go
- cmd/oras/repository/tags.go
> chore: use short names for repository commands

- cmd/oras/push.go
> fix: only fallback to OCI image when current media type is OCI artifact

- cmd/oras/attach.go
> chore: add subject reference into attach output

- cmd/oras/blob/delete.go
- cmd/oras/internal/option/confirmation.go
- cmd/oras/manifest/delete.go
> feat!: alias `remove` to `delete` and rename confirmation flag to `force`

- cmd/oras/discover.go
- cmd/oras/repository/ls.go
- cmd/oras/repository/tags.go
> fix: add stdin password for `discover`, `repo ls` and `repo tags`

- cmd/oras/discover.go
> fix: mandates empty referrer to empty array

- .github/workflows/release-ghcr.yml
- .goreleaser.yml
- Makefile
Resolves #731  
With this PR s390x release and image is added to oras. I build the binary and image for s390x and tested it on s390x architecture.
Binary:
```
[user@build oras]$ goreleaser build --snapshot
• starting build...
• loading config file                              file=.goreleaser.yml
• loading environment variables
• getting and validating git state
• ignoring errors because this is a snapshot     error=git doesn't contain any tags. Either add a tag or use --snapshot
• building...                                    commit=09e997a40fdf09b262d9e7b8cd58ecc262926e07 latest tag=v0.0.0
• pipe skipped                                   reason=disabled during snapshot mode
• parsing tag
• setting defaults
• DEPRECATED: `archives.rlcp` will be the default soon, check …
```
> feat: add s390x release and image to support s390x architecture

- cmd/oras/discover.go
- go.mod
- go.sum
This PR enriches tree output of `oras discover`. Artifact annotations will be shown in yaml format if `--verbose` flag is set.
Resolves #631
```
$ IMAGE="localhost:5000/test:anno"
$ oras-demo push $IMAGE image
Uploading 254eddf15d95 image
Uploaded  254eddf15d95 image
Pushed localhost:5000/test:anno
Digest: sha256:93305aefab90f837c555e42afcce5a3d92e23180d5dc64e37363d78d65c93306
$ oras-demo attach $IMAGE sig -a "key: "="value ' " --artifact-type test.anno
Uploading 0a017e570e0b sig
Uploaded  0a017e570e0b sig
Attached to localhost:5000/test@sha256:93305aefab90f837c555e42afcce5a3d92e23180d5dc64e37363d78d65c93306
Digest: sha256:0f6ac3195806949d22ac6eaab804fa4fd5c25974acdfb003ddb4f24cc1b6da62
$ oras-demo attach $IMAGE -a "key"="value" --artifact-type test.anno
Uploading empty artifact
Attached …
```
> feat: show annotations in `oras discover` tree format output

- cmd/oras/blob/delete.go
- cmd/oras/internal/option/confirmation.go
- cmd/oras/internal/option/confirmation_test.go
- cmd/oras/manifest/delete.go
- test/e2e/go.work.sum
- test/e2e/suite/command/blob.go
- test/e2e/suite/command/manifest.go
> feat!: force deleting a non-existent blob/manifest

- .github/workflows/build.yml
- test/e2e/internal/utils/init.go
- test/e2e/internal/utils/registry.go
- test/e2e/suite/command/push.go
- test/e2e/suite/scenario/const.go
- test/e2e/suite/scenario/oci_artifact.go
- test/e2e/suite/scenario/oci_image.go
- test/e2e/testdata/files/foobar/to-be-attached
> test(e2e): add oci artifact spec for common registry users

- cmd/oras/cp.go
- cmd/oras/internal/display/print.go
- cmd/oras/internal/errors/errors.go
- cmd/oras/internal/fileref/unix.go
- cmd/oras/internal/fileref/windows.go
- cmd/oras/internal/fileref/windows_test.go
- cmd/oras/internal/option/target.go
- cmd/oras/internal/option/target_test.go
- cmd/oras/internal/option/target_windows_test.go
- cmd/oras/manifest/push.go
- cmd/oras/push.go
- cmd/oras/tag/tag.go
- go.mod
- go.sum
> feat(oci-layout): support in `oras cp`

- cmd/oras/manifest/fetch.go
> fix: support fetching manifest in oci image layout

- cmd/oras/attach.go
- cmd/oras/internal/option/remote.go
- cmd/oras/internal/option/target.go
1. Fix flags `--from-distribution-spec` and `--to-distribution-spec` for `oras copy`
2. Fix the flag `--distribution-spec` for `oras attach`
This PR removes the check when specifying `--distribution-spec` for OCI layout.
Fixes: #770, #771
> fix: fix bugs related to the spec `--distribution-spec`

- .github/workflows/release-github.yml
- Dockerfile
1. Updated golang version to `1.19.5` for GitHub action
2. Updated golang version to `1.19.5` in dockerfile 
3. Updated alpine version to `3.17.1` in dockerfile
Signed-off-by: Sylvia Lei <lixlei@microsoft.com>
> bump: upgrade golang and alpine versions

- cmd/oras/repository/ls.go
- cmd/oras/repository/ls_test.go
- test/e2e/internal/utils/testdata.go
- test/e2e/suite/command/repo.go
Resolves #733 
Test output on terminal:
> feat: suppport repo ls sub-namespace

- Makefile
Latest command `oras repository ls` requires go 1.20
> fix: Have make file fail with wrong go version

- cmd/oras/attach.go
- cmd/oras/discover.go
- cmd/oras/internal/option/target.go
Changes in this PR prints resolved digest for root node of tree-view output in `oras discover`.
Resolves #789
> feat!: show subject digest in oras discover

- .github/licenserc.yml
- CODEOWNERS
Add [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) based on the [OWNERS.md](https://github.com/oras-project/oras/blob/main/OWNERS.md) file.
> chore: add CODEOWNERS based on OWNERS.md

- cmd/oras/repository/ls.go
- internal/repository/repository.go
- internal/repository/repository_test.go
Putting it in `cmd/oras/internal` will trigger code coverage scan on command declaration code, which effects our code coverage.
> chore: move ParseRepoPath to internal package

- CODEOWNERS
- MAINTAINERS.md
Nominate Billy Zha (@qweeah) as a maintainer of the `oras` repository.
Billy has contributed and merged 103 PRs to the `main` branch in the last 9 months.
> chore: add Billy Zha as a maintainer

- CODEOWNERS
- MAINTAINERS.md
Nominate Terry Howe (@TerryHowe) as a maintainer of the `oras` repository.
Terry opened 8 issues and 8 PRs (2 merged) in the past 2 months. Terry is also active in other open issues.
> chore: add Terry Howe as a maintainer

- cmd/oras/pull.go
Fixes #815 
We should delete the temp file after pulling the image to reduce storage usage
> fix: lazy close file store

- .github/PULL_REQUEST_TEMPLATE.md
Add a PR template so contributors have some guidelines.
> chore: Add basic PR template

- cmd/oras/repository/tags.go
Add a ability for the `oras repo tags` command to get the tags associated with a specified digest or tag. Given a tag, it will return the digest. Given a digest, it will return the tag.
Closes: https://github.com/oras-project/oras/issues/799
Signed-off-by: Terry Howe <tlhowe@amazon.com>
> feat: Add ability query tags for `oras repo tags` command

- test/e2e/internal/testdata/foobar/const.go
- test/e2e/suite/command/repo.go
This PR adds E2E test specs for filtered tag listing.
Fixes #829
> test(e2e): specs for filtered tag listing

- internal/graph/graph_test.go
This PR fixes a flaky unit test case found in ([CI logs](https://github.com/oras-project/oras/actions/runs/4260457314/jobs/7413642377#step:5:315)). 
The case is comparing a referrer array with provided value, which might fail when order of the elements is different. Reduced the length of array to one so the test result is determined.
> fix: flaky test on multi referrers

- cmd/oras/internal/option/remote.go
- cmd/oras/internal/option/target.go
This PR fix a bug in `oras cp`: when copying with `--resolve` provided for destination target, the provided value will be silently ignored.
Fixes #842 
> fix: support binary target in `oras cp`

- cmd/oras/internal/option/remote.go
- test/e2e/suite/auth/auth.go
This PR fixes a bug in `oras cp`: Registry credential configuration file specified via `--registry-config` will not work for destination registry target. 
This pr introduces flags, `--from-registry-config` and `--to-registry-config`, for source and destination registry respectively when copying. Since docker config only supports storing one credential per config file, this feature will be useful when copying between repositories with different token scope requirement in the same registry.
Fixes #846 
> fix!: support multiple config files in `oras cp`

- cmd/oras/internal/option/remote.go
Resolves #845
E2E tests will be added in #837.
> feat: support --header for oras cp

- cmd/oras/cp.go
Improves Error message on oras copy.go with non-existent tags
Fixes #791 
> fix: Improve error message on oras copy.go with  non-existent tags

- cmd/oras/attach.go
- cmd/oras/internal/option/spec.go
- cmd/oras/push.go
- test/e2e/suite/command/push.go
This PR changes the default media type of `oras push` and `oras attach` by removing the auto-conversion of the manifest type.
Resolves #782 
> feat!: disable auto type conversion for manifests

- .github/workflows/release-github.yml
- Dockerfile
This updates the go version of binary build and container build.
> bump: update go to 1.20.1

- README.md
Each ORAS sub-project should have a section in the README.md about setting up a development environment, since each sub-project is unique.
> docs: Add development environment section to readme

- internal/trace/transport.go
> feat!: improve debug log readability

- cmd/oras/blob/cmd.go
- cmd/oras/blob/delete.go
- cmd/oras/blob/fetch.go
- cmd/oras/blob/push.go
- cmd/oras/cp.go
- cmd/oras/internal/option/spec.go
- cmd/oras/internal/option/target.go
- cmd/oras/main.go
- cmd/oras/manifest/cmd.go
- cmd/oras/manifest/delete.go
- cmd/oras/manifest/fetch.go
- cmd/oras/manifest/fetch_config.go
- cmd/oras/manifest/push.go
- cmd/oras/pull.go
- cmd/oras/repo/cmd.go
- cmd/oras/repo/ls.go
- cmd/oras/repo/tags.go
- cmd/oras/tag/tag.go
- test/e2e/internal/testdata/feature/feature.go
- test/e2e/suite/command/attach.go
- test/e2e/suite/command/blob.go
- test/e2e/suite/command/cp.go
- test/e2e/suite/command/discover.go
- test/e2e/suite/command/manifest.go
- test/e2e/suite/command/pull.go
- test/e2e/suite/command/push.go
- test/e2e/suite/command/repo.go
- test/e2e/suite/command/tag.go
This PR updates feature marks to commands and features as summarized below:
1) stable commands need to remove preview mark
- `oras blob`
- `oras blob fetch`
- `oras blob delete`
- `oras blob push`
- `oras manifest`
- `oras manifest fetch`
- `oras manifest fetch-config`
- `oras manifest delete`
- `oras manifest push`
- `oras repo`
- `oras repo ls`
- `oras repo tags`
- `oras cp`
2) preview commands
- `oras attach`, `oras discover`: since the command always involves referrer API change, GA requires distribution-spec v1.1 release
3) experimental commands
none
4) preview features
- `--distribution-spec`: oci distribution spec v1.1 is not released
- `oras pull --include-subject`: image with subject will be defined in oci image-spec v1.1
- `oras cp …
> doc: add feature marks to cmd description and log

- test/e2e/suite/command/discover.go
This PR adds e2e test specs, its review depends on merge of #869.
Fixes #870 
> test(e2e): OCI layout specs for `oras discover`

- test/e2e/internal/utils/exec.go
- test/e2e/internal/utils/match/request.go
- test/e2e/suite/command/custom_header.go
> test: add header e2e test cases for `oras cp`

- test/e2e/suite/command/attach.go
This PR adds E2E specs on OCI layout supports provided by `oras attach`
Fixes #881 
> test(e2e): OCI layout specs for `oras attach`

- test/e2e/internal/utils/match/status.go
- test/e2e/suite/command/pull.go
This PR adds e2e tests.
Fixes #884
> test(e2e): add test specs for `oras pull`

- test/e2e/internal/utils/match/keywords.go
- test/e2e/internal/utils/match/request.go
- test/e2e/internal/utils/match/status.go
- test/e2e/suite/command/custom_header.go
- test/e2e/suite/command/push.go
- test/e2e/suite/scenario/oci_artifact.go
- test/e2e/suite/scenario/oci_image.go
This PR does below cleanup works on e2e tests.
- Use `ginkgo.Fail` instead of `panic` in test result matching.
- Make test folder preparation code more nit.
> chore: e2e test code clean

- test/e2e/suite/command/manifest.go
> test: add e2e tests for manifest fetch-config under oci-layout

- cmd/oras/manifest/fetch.go
- test/e2e/suite/command/manifest.go
> fix: add error when using media type assertion with oci layout

- cmd/oras/manifest/push.go
- test/e2e/suite/command/manifest.go
This PR fixes a bug and added e2e tests.
Fixes #891 
> fix: return error if content and password are both read from stdin

- go.mod
- go.sum
- test/e2e/go.mod
- test/e2e/suite/command/manifest.go
This PR adds e2e test specs for `oras manifest push`
Fixes #879 
> test(e2e): layout specs for `oras manifest push`

- go.mod
- go.sum
- test/e2e/go.mod
Bumps oras-go to 2.0.2
Fixes #883 
> build(deps): bump oras.land/oras-go/v2 to 2.0.2

- cmd/oras/attach.go
- cmd/oras/blob/delete.go
- cmd/oras/blob/fetch.go
- cmd/oras/blob/push.go
- cmd/oras/cp.go
- cmd/oras/discover.go
- cmd/oras/internal/option/common.go
- cmd/oras/login.go
- cmd/oras/manifest/delete.go
- cmd/oras/manifest/fetch.go
- cmd/oras/manifest/fetch_config.go
- cmd/oras/manifest/push.go
- cmd/oras/pull.go
- cmd/oras/push.go
- cmd/oras/repo/ls.go
- cmd/oras/repo/tags.go
- cmd/oras/tag/tag.go
- internal/trace/context.go
Partial https://github.com/oras-project/oras/issues/786
> refactor: Logger initializes logging

- cmd/oras/internal/option/remote_test.go
- cmd/oras/pull.go
- internal/crypto/certificate_test.go
- internal/graph/graph_test.go
This PR introduces no change but only does some code clean and makes code coverage looks better.
> test(cov): make unit tests cover more

- test/e2e/suite/command/tag.go
> test(e2e): OCI layout specs for `oras tag`

- .github/workflows/build.yml
- test/e2e/scripts/e2e.sh
- test/e2e/suite/command/discover.go
- test/e2e/suite/command/manifest.go
As a follow-up of #924, this PR moves the action of coverage data generation out of e2e run script.
Also added some e2e specs to validate the changes.
> test: make e2e coverage data in action

- Dockerfile
The change follows https://docs.docker.com/build/guide/multi-platform/#build-using-cross-compilation to switch oras docker release build to cross-compilation. It boosts the build performance by ~7x.
[Existing using emulation](https://github.com/oras-project/oras/actions/runs/4467009705/jobs/7845927060): 12m 9s. 
[New using cross-compilation ](https://github.com/northtyphoon/oras/actions/runs/4832631679/jobs/8611648375): 1m 39s
> build: using cross compilation in docker build

- CONTRIBUTING.md
**This Pull Request addresses the issue of the incorrect link in CONTRIBUTING.md. The previous link was leading to the wrong page, causing confusion for users. In this PR, I have corrected the link to point to the intended web page, ensuring accurate and relevant information is accessible to users. Please review and merge this PR.**:
Fixes #950
> fixed the link in the file : oras/CONTRIBUTING.md

- .github/dependabot.yml
This added dependabot config for nest e2e test module.
Fixes #876 
> build: add dependabot for e2e module

- cmd/oras/internal/option/spec.go
- test/e2e/suite/command/attach.go
This PR fixes a minor bug for the spec flag value checking.
Fixes #897
> fix: correct spec flag description

- Makefile
> Add help to make file

- cmd/oras/internal/option/packer.go
- cmd/oras/root/attach.go
- cmd/oras/root/pull.go
- cmd/oras/root/push.go
I just tried to push an artifact file from linux environment from a absolute path or from different directory. The path is implicitly taken by the oras cli or oras sdk when I pushed it. Like the file was in a directory /home/vts/1/a.exe. and I pushed from /home/test. I am ok if the push fails stating me that the file is not in the current directory and for security reasons you have to be in same working directory. But the push passes and pull fails . So disallow is a much better option. I am sure when I used ORAS python SDK it did fail with error stating as here https://github.com/oras-project/oras-py/blob/209c9b98043a00d1b04789cc2967ca7021dc5b2e/oras/provider.py#L651 . The CLI should have same behaviour as SDK. Then push and pull are coherent. It …
> fix: enforce path validation for push/attach and improve path traversal failure message for pull

- cmd/oras/root/attach.go
- cmd/oras/root/blob/fetch.go
- cmd/oras/root/blob/push.go
- cmd/oras/root/cp.go
- cmd/oras/root/discover.go
- cmd/oras/root/manifest/fetch.go
- cmd/oras/root/manifest/fetch_config.go
- cmd/oras/root/manifest/push.go
- cmd/oras/root/pull.go
- cmd/oras/root/push.go
- cmd/oras/root/repo/tags.go
- cmd/oras/root/tag.go
This PR mentioned OCI layout support in related command help doc.
Fixes #904
> chore: update help doc with OCI layout support

- .github/workflows/release-github.yml
- Dockerfile
- internal/version/version.go
This PR updates the minor version of oras to prepare for 1.1.0 release.
> chore: update minor version

- cmd/oras/root/discover.go
- go.mod
- go.sum
- internal/tree/node.go
- internal/tree/node_test.go
- internal/tree/printer.go
- internal/tree/printer_test.go
- Properly print tree for `oras discover`
- Remove the dependency of `github.com/need-being/go-tree`, which is no longer maintained and does not have any tests
Fixes #1003
> fix: properly print tree for `oras discover`

- .github/workflows/release-github.yml
- Dockerfile
This PR updates the version of Golang for binary build and GHCR container build.
> bump: update golang from 1.20.2 to 1.20.5

- internal/version/version.go
This PR proposes to cut out a branch for oras CLI based on edfc253f8cc1bb71471158a55fb71fd7f723c846 and release.  This new branch will be named as `release-1.1` and tagged as `v1.1.0-rc.1` for releasing. At least 3 approvals are needed from the 5 owners.
Below is a summary of change notes since [v1.0.0](https://github.com/oras-project/oras/releases/tag/v1.0.0):
- `oras push` and `oras attach` generates unwanted manifest file (#995)
- Path validation not enforced for `oras attach` and `oras push` (#983, #980, #973)
- Wrong error information when `--distribution-spec` is provided with invalid value (#897)  
- Tree view print bug in `oras discover` (#1003)
- Add a new flag `--skip-delete-referrers` to allow oras commands to skip referrer index clean up …
> bump: tag and release ORAS CLI v1.1.0-rc.1

- CONTRIBUTING.md
- README.md
This PR fixes the links. Fixes #1017 
> chore: fix the links in project readme

- .github/workflows/release-ghcr.yml
This PR removes the usage of `set-output` in Github Actions. Tested in my own fork and it works as expected: https://github.com/qweeah/oras/actions/runs/5521156830/jobs/10068846025
Fixes #1018 
> chore: update container build prepare job output in Github Actions

- internal/credential/store.go
- internal/credential/store_test.go
This PR adds a unit test file for `internal/credential/store.go` to increase its code coverage from 78.57% to 100%.
Fixes #
This PR is a small part of https://github.com/oras-project/oras/issues/972
> test: add unit test for error scenario in `internal/credential/store.go`

- .github/workflows/golangci-lint.yml
The following are the places that's giving some errors as of now according to the linter. 
<details><summary> output of running golangci locally </summary>
<p>
```bash
$ golangci-lint run
cmd/oras/root/attach.go:94:22: Error return value of `cmd.MarkFlagRequired` is not checked (errcheck)
cmd.MarkFlagRequired("artifact-type")
^
cmd/oras/root/discover.go:191:13: Error return value is not checked (errcheck)
printJSON(ref)
^
cmd/oras/internal/display/print.go:119:9: Error return value is not checked (errcheck)
Print("Tagging", ref)
^
cmd/oras/internal/display/print.go:139:9: Error return value is not checked (errcheck)
Print("Tagging", ref)
^
cmd/oras/internal/option/packer_test.go:73:14: Error return value of `os.WriteFile` is not checked (errcheck) …
```
> chore: use golangci lint

- Makefile
- test/e2e/suite/command/attach.go
- test/e2e/suite/command/cp.go
- test/e2e/suite/command/manifest.go
> fix: correct e2e specs and CI check configuration

- .github/stale.yml
Enables the oras repo to run stale action at 1:30 every day to label, stale or close inactive PRs and issues. 
See - https://github.com/marketplace/actions/close-stale-issues
> workflow: add github stale action

- internal/version/version.go
This PR proposes to tag oras CLI v1.0.1 based on https://github.com/oras-project/oras/pull/1048/commits/acf147b7564f44f8637dc59937d6167e5427e612 and release. This merged commit in branch release 1.0 will be tagged as v1.0.1 for releasing. At least 3 approvals are needed from the 5 owners.
Below is a summary of change notes since [v1.0.0](https://github.com/oras-project/oras/releases/tag/v1.0.0):
- `oras push` and `oras attach` generates unwanted manifest file (#995)
- Path validation not enforced for `oras attach` and `oras push` (#983, #980, #973)
- Wrong error information when `--distribution-spec` is provided with invalid value (#897)  
- Tree view print bug in `oras discover` (#1003)
- Improve UX
- `oras pull` prints better error msg when path …
> bump: tag and release ORAS CLI v1.0.1

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/feature-request.yaml
This PR adds a `triage` label to the ORAS issue templates. New issues will be labeled with `triage` so that we can quickly find the issues that need to be triaged.
> chore: add triage labels

- cmd/oras/root/tag.go
- test/e2e/suite/command/tag.go
This PR improves the readability of error info when an invalid reference is provided:
```console
$ oras tag list test
Error: unable to add tag for 'list': invalid reference: missing repository
```
> chore: make error returned by `oras tag` more readable

- cmd/oras/internal/option/spec.go
- cmd/oras/root/attach.go
- cmd/oras/root/push.go
- go.mod
- go.sum
- test/e2e/go.mod
- test/e2e/go.sum
- test/e2e/suite/scenario/oci_artifact.go
This PR uses `PackManifest` in push and attach.
> bump: use new packing function in oras-go

- cmd/oras/internal/option/spec.go
- cmd/oras/root/push.go
This PR updates the pack option of image spec from `PackType` to `PackVersion`
> chore: align naming of pack option to oras-go

- internal/version/version.go
This PR proposes to tag for oras CLI based on 443242e41d469a911af6fa68f3338fcfb2f5f268 and release.  The new tag will be named as `v1.1.0-rc.2` for releasing. At least 3 approvals are needed from the 5 owners.
Below is a summary of change notes since [v1.1.0-rc.1](https://github.com/oras-project/oras/releases/tag/v1.1.0-rc.1):
- Pack OCI image compliant to [OCI image spec v1.1.0-rc4](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc4/manifest.md#oci-image-manifest-specification) (#1043, #1009)
- `oras attach` and `oras push` no longer build manifests with manifest type `application/vnd.oci.artifact.manifest.v1+json`
- Remove the experimental flag `--image-spec` from `oras attach`
- `oras push` builds artifact manifest following [this …
> bump: tag and release ORAS CLI v1.1.0-rc.2

- cmd/oras/root/attach.go
- cmd/oras/root/push.go
- internal/registryutil/auth.go
Add `pull, push` scope hints before calling `Copy` for `oras push` and `oras attach`. 
This can potentially save 2 requests for each command.
```sh
oras push $myreg/$myrepo:$mytag --debug
```
request `#0`: HEAD manifest digest - 401
request `#1`: POST token (scope: pull) - 200
request `#2`: HEAD manifest digest - 404
request `#3`: HEAD config ({}) - 404
<ins>request `#4`: POST config ({}) - 401</ins>
<ins>request `#5`: POST token (scope: pull, push) - 200</ins>
request `#6`: POST config ({}) - 202
request `#7`: PUT config ({}) - 201
request `#8`: PUT manifest tag - 201
request `#0`: HEAD manifest digest - 401
request `#1`: POST token (scope: pull) - 200
request `#2`: HEAD manifest digest - 404
request `#3`: HEAD config ({}) - 404
request `#4`: POST …
> perf: save auth requests for push and attach

- cmd/oras/root/push.go
This PR updates example for `oras push` command.
> doc: update example for `oras push`

- internal/version/version.go
This PR proposes to tag `v1.1.0` and checkout `release-1.1` based on 7079c468a06fb5815c99395eb4aaf46dd459d3fa and release. At least 3 approvals are needed from the 5 owners.
Below is a summary of change notes since [v1.1.0-rc.2](https://github.com/oras-project/oras/releases/tag/v1.1.0-rc.2):
- Improve performance
- Reduced auth requests for push and attach (#1084)
- Improve documentation
- Updated security guide (#1017)
- Update dependencies
- Bump oras-go to 2.3.0 
- Improve tests
- Use ZOT in E2E tests (#1071)
- Added E2E tests to cover spec update (#1092)
Detailed change logs:
* bump: tag and release ORAS CLI v1.1.0-rc.2 by @qweeah in https://github.com/oras-project/oras/pull/1078
* test(e2e): add zot as a testing backend by @qweeah in …
> bump: tag and release ORAS CLI v1.1.0

- cmd/oras/internal/option/remote.go
- cmd/oras/internal/option/remote_test.go
This PR allows user to specify `--plain-http=false` for a registry named `localhost`
Fixes #1106 
> fix: allow HTTPS for localhost

- cmd/oras/internal/option/remote.go
- cmd/oras/internal/option/spec.go
- cmd/oras/root/attach.go
- cmd/oras/root/blob/delete.go
- cmd/oras/root/manifest/delete.go
- cmd/oras/root/push.go
- internal/registryutil/auth.go
This PR optimize the request count of `oras blob delete` and `oras manifest delete` when using against a remote registry.
When deleting a manifest via tag from registry, the requests are optimized as below:
**Before**
request `#0`: HEAD manifest tag- 401
request `#1`: GET token (scope: pull) - 200
request `#2`: HEAD manifest tag- 200
request `#3`: GET manifest digest- 200
request `#4`: DELETE manifest digest 401
request `#5`: GET token (scope: delete, pull) - 200
request `#6`: DELETE manifest digest - 202
**After**
request `#0`: HEAD manifest tag- 401
request `#1`: GET token (scope: pull, delete, push) - 200
request `#2`: HEAD manifest tag- 200
request `#3`: GET manifest digest- 200
request `#4`: DELETE manifest digest - 202
Same for `oras blob …
> perf: optimize request count for manifest and blob deletion

- cmd/oras/internal/option/remote.go
- cmd/oras/internal/option/spec.go
- cmd/oras/root/attach.go
- cmd/oras/root/blob/delete.go
- cmd/oras/root/manifest/delete.go
- cmd/oras/root/push.go
- internal/registryutil/auth.go
Reverts oras-project/oras#1109
> revert: "perf: optimize request count for manifest and blob deletion"

- test/e2e/suite/command/attach.go
- test/e2e/suite/command/push.go
> chore: fix typo

- cmd/oras/root/cp.go
- internal/docker/mediatype.go
- internal/graph/graph.go
- test/e2e/internal/testdata/multi_arch/const.go
- test/e2e/suite/command/cp.go
- test/e2e/suite/command/pull.go
- test/e2e/testdata/zot/command/images/blobs/sha256/b2a5fcfb112ccde647a5a3dc0215c2c9e7d0ce598924a5ec48aa85beca048286
- test/e2e/testdata/zot/command/images/index.json
This PR changes `oras cp` to recursively copy referrers of platform-specific images in an index or manifest list.
Resolves #816
> feat: support copying referrers for multi-arch images

- cmd/oras/root/cp.go
Fix a bug when `oras cp -r` a loop index.
Fixes #1129
> fix: remove root from virtual referrers

- .github/workflows/release-ghcr.yml
- .goreleaser.yml
- Makefile
Release for more architectures, as oras is getting more popular :tada: and some use cases require more exotic architectures.
Also improving the reproducibility of release artifacts by
- trimming paths (making the build independent from the current directory)
- set build ID to empty string
- set binary timestamp to commit timestamp
- strip binary (reduces size from 9.2MB to 8.5MB)
**Which issue(s) this PR fixes**:
Fixes #1111
> build: release ppc64le/riscv64 and improve reproducibility 

- internal/trace/transport.go
- test/e2e/suite/command/cp.go
This PR fixes a bug that causes duplicated numbering for debug logs
Fixes #1096
> fix: resolve duplicated debug log for `oras cp`

- cmd/oras/internal/errors/errors.go
- cmd/oras/internal/option/remote.go
- cmd/oras/internal/option/target.go
- cmd/oras/root/manifest/delete.go
- test/e2e/suite/command/discover.go
- test/e2e/suite/command/manifest.go
The errors from the oras CLI does not show the actual value that was provided. 
The following PR updates the erros to include the actual user provided reference here - 
```
$ oras copy test someotherregistry.azurecr.ui/myimage:v1
Error: "test": invalid reference: missing registry or repository
$ oras copy test.com someotherregistry.azurecr.ui/myimage:v1
Error: "test.com": invalid reference: missing registry or repository
$ oras copy test.com/test someotherregistry.azurecr.ui/myimage:v1
Error: "test.com/test": no tag or digest when expecting <name:tag|name@digest>
$ oras copy test.com/test: someotherregistry.azurecr.ui/myimage:v1
Error: "test.com/test:": no tag or digest when expecting <name:tag|name@digest>
$ oras copy test.com/test@ …
```
> chore: add reference details to registry errors

- cmd/oras/internal/display/progress/status.go
- cmd/oras/internal/display/progress/status_test.go
- cmd/oras/root/pull.go
Update the message for oras pull of an image to something actionable - 
The current outputs looks like this 
```
❯ oras pull localhost:5000/hello-world:latest
Downloaded empty artifact
Pulled [registry] localhost:5000/hello-world:latest
Digest: sha256:7e9b6e7ba2842c91cf49f3e214d04a7a496f8214356f41d81a6e6dcad11f11e3
```
The PR modifies this to 
```
❯ go run ./cmd/oras  pull localhost:5000/hello-world:latest
Skipped pulling layers without "org.opencontainers.image.title"
Use 'oras copy localhost:5000/hello-world:latest --to-oci-layout <layout-dir>' to pull all layers.
``` 
Also changed to `✓` character for checkmark.
> feat: remove empty artifact CLI message and show hints for pulling OCI image layout

- cmd/oras/root/pull.go
This PR avoids wrong hinting on unnamed manifest/index in verbose mode.
Suppose we have below manifest stored in registry
```console
$ oras manifest fetch --pretty localhost:5000/test:config                                                         
{
"schemaVersion": 2,
"mediaType": "application/vnd.oci.image.manifest.v1+json",
"artifactType": "my.test/example",
"config": {
"mediaType": "bar/test",
"digest": "sha256:2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae",
"size": 3
},
"layers": [
{
"mediaType": "application/vnd.oci.image.layer.v1.tar",
"digest": "sha256:2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae",
"size": 3,
"annotations": {
"org.opencontainers.image.title": "foo"
}
}
],
"annotations": { …
```
> fix: should not print copy hint for manifest in verbose mode

- cmd/oras/internal/option/common.go
- cmd/oras/internal/option/common_unix_test.go
This PR makes `--debug` flag imply `--no-tty` flag.
Related to #940 
> feat: make `--debug` imply `--no-tty`

- cmd/oras/root/cp.go
- cmd/oras/root/pull.go
- cmd/oras/root/push.go
- test/e2e/suite/command/pull.go
The recommendation to use ORAS copy will be skipped if the only layer not downloaded is the config.
> fix: avoid copy suggestion when only config is skipped

- cmd/oras/root/pull.go
#1164 has a regression which only print skip hints for empty layers. This PR fixed it. Tested with below command. Will add E2E tests to cover all possibility for the skip hint
```console
✗ ./bin/linux/amd64/oras pull ghcr.io/oras-project/oras:v1.1.0 -o pulled --platform linux/amd64
✓ Skipped     application/vnd.oci.image.layer.v1.tar+gzip                                                                                                                                                                                                                                            3.21/3.21 MB 100.00%     0s
└─ sha256:8921db27df2831fa6eaa85321205a2470c669b855f3ec95d5a3c2b46de0442c9 
✓ Skipped     application/vnd.oci.image.layer.v1.tar+gzip …
```
> fix: resolve regression made in #1164

- cmd/oras/root/pull.go
This PR avoids potential race condition when concurrently pulling an image.
> fix: atomic bool for layer skipped during pulling

- cmd/oras/root/repo/ls.go
Improves the error message to show the registry and namespace when catalog listing fails. 
```bash
$ oras repo ls docker.io
Error: could not list repositories for "registry-1.docker.io"
GET "https://registry-1.docker.io/v2/_catalog": GET "https://auth.docker.io/token?scope=registry%3Acatalog%3A%2A&service=registry.docker.io": response status code 400: Bad Request
```
```bash 
$ oras repo ls docker.io/python
Error: could not list repositories for "registry-1.docker.io" with prefix "python/"
GET "https://registry-1.docker.io/v2/_catalog": GET "https://auth.docker.io/token?scope=registry%3Acatalog%3A%2A&service=registry.docker.io": response status code 400: Bad Request
```
> fix: update error message for repo ls

- cmd/oras/internal/display/progress/status.go
- cmd/oras/internal/display/progress/status_test.go
> fix: avoid overflow in progress bar percentage

- cmd/oras/internal/display/console/console.go
This PR makes the TTY output easier to copy.
Fixes #1166
> chore(ux): add newline to make TTY output copy friendly

- test/e2e/suite/command/blob.go
This PR corrects a false positive e2e spec.
> test(e2e): fix a false positive test for `blob get`

- cmd/oras/root/cmd.go
- cmd/oras/root/resolve.go
- test/e2e/internal/utils/testdata.go
- test/e2e/suite/command/resolve.go
This is an update with a test and flags based of PR from @amands98. 
@amands98  if you would like to combine these commits I'm more than happy to send a PR to your branch. 
- Resolve command with support for platform output of fully qualified reference - 
``` 
❯ oras resolve -l localhost:5000/command/artifacts:multi
localhost:5000/command/artifacts@sha256:e2bfc9cc6a84ec2d7365b5a28c6bc5806b7fa581c9ad7883be955a64e3cc034f
```
```
❯ oras resolve  localhost:5000/command/artifacts:multi --platform linux/amd64
sha256:9d84a5716c66a1d1b9c13f8ed157ba7d1edfe7f9b8766728b8a1f25c0d9c14c1
```
```
❯ oras digest docker.io/library/hello-world:latest
sha256:88ec0acaa3ec199d3b7eaf73588f4518c25f9d34f58ce9a0df68429c5af48e8d
```
Fixes #907.
> feat: add resolve command

- cmd/oras/root/resolve.go
- test/e2e/suite/auth/auth.go
- test/e2e/suite/command/resolve.go
This PR adds e2e specs for `oras reslove`.
> test(e2e): add test for `resolve` command

- cmd/oras/root/attach.go
This PR improves help docs of `oras attach`.
> doc: add example for attach with custom layer media type

- cmd/oras/internal/display/track/target.go
- cmd/oras/root/attach.go
- cmd/oras/root/pull.go
- cmd/oras/root/push.go
This PR fixed the bug mentioned in #1208 with minimal refactoring on `getTrackedTarget`
> fix: bug in pushing with multiple tags

- cmd/oras/internal/option/target.go
- cmd/oras/internal/option/target_test.go
- cmd/oras/root/tag.go
- test/e2e/suite/command/tag.go
> chore(ux): improve error message for `oras tag list`

- cmd/oras/root/cp.go
- cmd/oras/root/discover.go
- go.mod
- go.sum
- internal/graph/graph.go
- internal/graph/graph_test.go
This PR bumps oras-go and applies the newly added registry.Referrers from oras-project/oras-go#659
> build(deps): bump oras-go/v2 to main branch

- cmd/oras/internal/option/spec.go
Fixes #1225. Current output after fix
```console
$ oras attach -h
...
--distribution-spec string                   [Preview] set OCI distribution spec version and API option for target. Options: v1.1-referrers-tag, v1.1-referrers-api
...
$ oras cp -h
...
--from-distribution-spec string                   [Preview] set OCI distribution spec version and API option for source target. Options: v1.1-referrers-tag, v1.1-referrers-api
...
--to-distribution-spec string                     [Preview] set OCI distribution spec version and API option for destination target. Options: v1.1-referrers-tag, v1.1-referrers-api
...
```
**Please check the …
> fix: resolve error in help doc of distribution spec flag

- .github/workflows/build.yml
Sometime codecov job might silently fail without calculating the code coverage and do checking(see [logs](https://github.com/oras-project/oras/actions/runs/7405557847/job/20148684470#step:8:32)). This PR enforces the success of codecov job with code check.
> build(ci): make coverage upload and calculation mandatory

- cmd/oras/internal/errors/errors.go
- cmd/oras/internal/option/target.go
- cmd/oras/root/attach.go
- cmd/oras/root/blob/delete.go
- cmd/oras/root/blob/fetch.go
- cmd/oras/root/cp.go
- cmd/oras/root/discover.go
- cmd/oras/root/manifest/delete.go
- cmd/oras/root/manifest/fetch.go
- cmd/oras/root/manifest/fetch_config.go
- cmd/oras/root/pull.go
- cmd/oras/root/resolve.go
- cmd/oras/root/tag.go
- test/e2e/suite/command/blob.go
- test/e2e/suite/command/cp.go
- test/e2e/suite/command/discover.go
- test/e2e/suite/command/manifest.go
- test/e2e/suite/command/resolve.go
improve error message for oras manifest fetch
Fixes #1211 and #1233 
Current display:
> chore(ux): improve error message for oras manifest fetch

- cmd/oras/root/attach.go
- test/e2e/suite/command/attach.go
> chore: improve error message when attaching with no file or annotation

- cmd/oras/root/attach.go
This PR fixes unexpected output error in the recommendation.
> fix: remove unwanted newline in attach error

- test/e2e/scripts/prepare.sh
This PR fixes the E2E test failure by updating the used image to `2.0.1`. ZOT removed an obsoleted RC image, which causes the E2E test preparation failure.
Fixes #1281
> fix(e2e): update ZOT image

- cmd/oras/internal/display/status/console/console_test.go
- cmd/oras/internal/display/status/console/testutils/testutils.go
- cmd/oras/internal/display/status/progress/status_test.go
- cmd/oras/internal/display/status/track/target_test.go
- cmd/oras/internal/display/status/tty_test.go
- cmd/oras/internal/option/common_unix_test.go
- cmd/oras/root/blob/fetch_test.go
- cmd/oras/root/blob/push_test.go
- cmd/oras/root/cp_test.go
- cmd/oras/root/pull_test.go
Removed `darwin` from go build constraint for pty-related operations. Tested on arm64 Mac and the tests pass.
Fixes #1277
> test(unit): exclude darwin from go build constraint

- cmd/oras/root/blob/push.go
- cmd/oras/root/login.go
- cmd/oras/root/logout.go
- cmd/oras/root/push.go
- cmd/oras/root/repo/ls.go
- cmd/oras/root/repo/tags.go
This is a minor refactor to make the command private methods consistent. Most of them take a cmd and not a context except for these six. The reason for this is to make logging and output more consistent across the commands and the`corbra.Command` has methods like `OutOrStdout`
Fixes #
> refactor: pass cobra.Command to all cmd exec functions

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/license-checker.yml
- .github/workflows/release-github.yml
Node 16 is deprecated and the v3 actions use it. These actions are available with a Node 20 runner with v4.
> build(actions): update github actions for Node 20

- .github/workflows/build.yml
It looks like there are problems with v4 coverage I was not aware off. Reverting for now.
https://github.com/codecov/codecov-action/issues/1292
> fix: Revert github actions coverage until fixed

- cmd/oras/root/blob/delete.go
- cmd/oras/root/blob/push.go
- cmd/oras/root/cp.go
- cmd/oras/root/discover.go
- cmd/oras/root/login.go
- cmd/oras/root/manifest/delete.go
- cmd/oras/root/manifest/push.go
- cmd/oras/root/pull.go
- cmd/oras/root/repo/ls.go
- cmd/oras/root/repo/tags.go
- cmd/oras/root/resolve.go
- cmd/oras/root/version.go
This contains the command refactor I did in another PR.
With this change, the output of a command can be set to something other than stdout. For example capture the output of a command:
```
var stringWriter strings.Builder
cmd := root.New()
cmd.SetArgs([]string{"repo", "ls", "mcr.microsoft.com"})
cmd.SetOutput(&stringWriter)
_ := cmd.Execute()
fmt.Println(stringWriter.String())
```
> feat: Use cobra.Command.OutOrStdout method for output

- cmd/oras/internal/option/spec.go
- cmd/oras/internal/option/target.go
- cmd/oras/internal/option/target_test.go
- cmd/oras/root/attach.go
- cmd/oras/root/push.go
- cmd/oras/root/tag.go
- go.mod
- go.sum
- test/e2e/go.mod
- test/e2e/go.sum
- test/e2e/suite/command/push.go
- test/e2e/suite/command/resolve.go
- test/e2e/suite/command/tag.go
> bump: bump `oras-go` to 2.5.0

- cmd/oras/internal/display/handler.go
- cmd/oras/internal/display/status/print.go
- cmd/oras/internal/display/status/text.go
This PR makes status output handlers use command output.
> refactor: use command output in status output

- cmd/oras/root/pull.go
Signed-off-by: rick <LinuxSuRen@users.noreply.github.com>
Fixes #
> chore: using const to replace string

- cmd/oras/internal/option/common.go
- cmd/oras/internal/option/packer.go
- cmd/oras/internal/option/parser.go
- cmd/oras/internal/option/parser_test.go
- cmd/oras/internal/option/platform.go
- cmd/oras/internal/option/platform_test.go
- cmd/oras/internal/option/remote.go
- cmd/oras/internal/option/target.go
- cmd/oras/internal/option/target_test.go
- cmd/oras/root/attach.go
- cmd/oras/root/blob/delete.go
- cmd/oras/root/blob/fetch.go
- cmd/oras/root/blob/push.go
- cmd/oras/root/cp.go
- cmd/oras/root/discover.go
- cmd/oras/root/login.go
- cmd/oras/root/manifest/delete.go
- cmd/oras/root/manifest/fetch.go
- cmd/oras/root/manifest/fetch_config.go
- cmd/oras/root/manifest/push.go
- cmd/oras/root/pull.go
- cmd/oras/root/push.go
- cmd/oras/root/repo/ls.go
- cmd/oras/root/repo/tags.go
- cmd/oras/root/resolve.go
- cmd/oras/root/tag.go
> refactor: make command accessible in option parser

- .github/workflows/golangci-lint.yml
This PR updates golang lint GHA
> bump(ci): update golangci-lint to v4

- cmd/oras/internal/display/metadata/text/push.go
- cmd/oras/internal/display/metadata/text/push_test.go
- test/e2e/suite/command/push.go
> feat: show artifact type when pushing files

- cmd/oras/internal/option/spec.go
- cmd/oras/root/push.go
- test/e2e/suite/command/push.go
`oras push` should return an error when `--config` is used, `--artifact-type` is not used and `--image-spec` is set to `v1.1`.
Fixes #1313 
> fix: oras push should return error when artifacttype is empty for spec 1.1

- cmd/oras/internal/option/spec.go
- cmd/oras/root/push.go
`auto` option for `--image-spec` is removed.
current display of `--image-spec` help info:
Fixes #1061 
> ux: improve the usage doc of --image-spec

- cmd/oras/root/attach.go
As a complement of #1309, this PR adds preview feature mark to allow future changes on the flag.
> chore: add preview feature mark to platform-specific attaching

- cmd/oras/internal/display/metadata/tree/discover.go
- test/e2e/suite/command/discover.go
> feat: oras discover should show a placeholder of artifactType if it's not presented

- cmd/oras/internal/option/spec.go
- test/e2e/suite/command/push.go
make --image-spec [Preview] from [Experimental].
Part of #1274 
> feat: make image spec preview

- cmd/oras/internal/option/remote.go
- cmd/oras/internal/option/remote_test.go
- cmd/oras/internal/option/target_test.go
- cmd/oras/root/blob/push.go
- cmd/oras/root/login.go
- cmd/oras/root/manifest/push.go
- test/e2e/suite/auth/auth.go
- test/e2e/suite/command/blob.go
- test/e2e/suite/command/cp.go
- test/e2e/suite/command/manifest.go
> feat: make --identity-token an alias of --password

- cmd/oras/internal/display/status/progress/status.go
- cmd/oras/internal/display/status/progress/status_test.go
This PR adds color to the TTY output.
- The spinner will be renderred in light yellow
- The done mark will be renderred in light green
- The progress bar will be renderred in light blue
> feat: add color to progress mark and bar

- cmd/oras/internal/display/metadata/model/descriptor.go
- cmd/oras/internal/display/metadata/model/discover.go
- cmd/oras/internal/display/metadata/model/fetched.go
- cmd/oras/internal/display/metadata/model/pull.go
- cmd/oras/internal/display/metadata/template/template.go
- cmd/oras/internal/display/metadata/template/template_test.go
- cmd/oras/internal/display/utils/json.go
- test/e2e/suite/command/attach.go
- test/e2e/suite/command/cp.go
- test/e2e/suite/command/discover.go
- test/e2e/suite/command/manifest.go
- test/e2e/suite/command/pull.go
- test/e2e/suite/command/push.go
- test/e2e/suite/scenario/oci_artifact.go
This PR makes all formattable names of the metadata output  lower cased.
Fixes #1342
> feat: make all go-template key lower-cased

- cmd/oras/internal/errors/errors.go
- cmd/oras/internal/option/remote.go
Improve error message when detecting conflicting flags. 
Current display:
Fixes #1340 
> feat: improve error message when detecting conflicting flags

- cmd/oras/internal/errors/errors.go
- cmd/oras/internal/errors/errors_test.go
- cmd/oras/internal/option/remote.go
- cmd/oras/root/discover.go
- test/e2e/suite/command/discover.go
> fix: fix error message when output is used before format for oras discover

- cmd/oras/root/manifest/fetch.go
- test/e2e/suite/command/manifest.go
return error when --format and --pretty are both used for `oras manifest fetch`. Need to rebase after #1354 is merged.
Fixes #1356 
> fix: return error when --format and --pretty are both used

- cmd/oras/root/manifest/fetch.go
- test/e2e/suite/command/manifest.go
> fix: ignore --pretty when --output is used for oras manifest fetch

- cmd/oras/internal/display/status/print.go
- cmd/oras/internal/display/status/print_test.go
I don't think we should consider print errors a problem most of the time and we should manage the output of the error to print only once.
> refactor: No error return for print

- docs/proposals/formatted-output.md
add spec: Formatted ORAS CLI output
Fixes #638
> doc(spec): formatted ORAS CLI output

- snapcraft.yaml
This PR added a fix to remove non-classic snap plugins in the snap build configuration. Will resolve [publish errors](https://github.com/oras-project/oras/actions/runs/9124299668) in the snap release
> fix: remove non-classic snap plugins

- cmd/oras/root/cp.go
This was the only difference I thought should be corrected in the CLI as far as the documentation
> fix: oras cp documentation

- cmd/oras/internal/display/status/deprecated.go
- cmd/oras/root/cp.go
- cmd/oras/root/cp_test.go
Remove last reference to deprecated PrintStatus method
> refactor: Get rid of deprecated PrintStatus method

- cmd/oras/internal/display/status/deprecated.go
- cmd/oras/internal/display/status/text.go
- cmd/oras/root/blob/push.go
- cmd/oras/root/blob/push_test.go
- cmd/oras/root/manifest/push.go
Removes deprecated PrintStatus method
> chore: Remove deprecated PrintStatus method

- cmd/oras/root/manifest/push.go
I missed this call in the last pull request. The printer is already available for manifest push.
> fix: remove call to deprecated print

- cmd/oras/internal/display/status/deprecated.go
- cmd/oras/root/cp.go
- cmd/oras/root/manifest/push.go
- cmd/oras/root/tag.go
Remove deprecated Print method
> chore: Remove deprecated Print method

- .github/workflows/release-github.yml
- .goreleaser.yml
Config changes to update `goreleaser`
> chore: Update goreleaser to v6 and configuration to v2

- cmd/oras/internal/display/status/deprecated.go
- cmd/oras/internal/display/status/text.go
- cmd/oras/internal/display/status/tty.go
- cmd/oras/internal/output/print.go
- cmd/oras/internal/output/print_test.go
- cmd/oras/root/blob/push.go
- cmd/oras/root/blob/push_test.go
- cmd/oras/root/cp.go
- cmd/oras/root/cp_test.go
- cmd/oras/root/manifest/push.go
- cmd/oras/root/tag.go
The printer is supposed to be a very generic output object and this change moves in that direction.
> refactor: Move printer to output package

- cmd/oras/internal/display/status/text.go
- cmd/oras/internal/display/status/tty.go
- cmd/oras/internal/display/status/utils.go
Just some clean up in the pull handlers.
> refactor: Clean up pull handlers

- cmd/oras/internal/display/status/text.go
- cmd/oras/internal/output/print.go
- cmd/oras/internal/output/print_test.go
- cmd/oras/root/blob/push.go
- cmd/oras/root/blob/push_test.go
- cmd/oras/root/cp.go
- cmd/oras/root/cp_test.go
- cmd/oras/root/manifest/push.go
- cmd/oras/root/tag.go
The verbose option should be owned by the printer.
> refactor: Move verbose into printer object

- cmd/oras/internal/display/status/text.go
- cmd/oras/internal/display/status/tty.go
- cmd/oras/internal/display/status/tty_test.go
- cmd/oras/internal/display/status/utils.go
As a follow up to #1407, this PR aligns the prompts naming for status handlers.
> refactor: clean status prompts

- cmd/oras/internal/display/handler.go
- cmd/oras/internal/display/handler_test.go
- cmd/oras/internal/option/format.go
- cmd/oras/root/attach.go
- cmd/oras/root/discover.go
- cmd/oras/root/manifest/fetch.go
- cmd/oras/root/pull.go
- cmd/oras/root/push.go
- test/e2e/internal/utils/help.go
- test/e2e/suite/command/attach.go
- test/e2e/suite/command/discover.go
- test/e2e/suite/command/manifest.go
- test/e2e/suite/command/pull.go
- test/e2e/suite/command/push.go
Introduce `text` as default format type for `pull`, `push`, `manifest fetch` and `attach` commands.
The only change in E2E experience is in the help document. Taking `oras attach` as an example:
**Before**
```console
> oras attach -h
...
--format string                               [Experimental] Format output using a custom template:
'json':         Print in JSON format
'go-template':  Print output using the given Go template
...
```
**After**
```console
> oras attach -h
...
--format string                               [Experimental] Format output using a custom template:
'json':         Print in JSON format
'go-template':  Print output using the given Go template
'text':         Print in text format (default "text")
...
```
> chore: Add format type text

- cmd/oras/internal/output/print_test.go
> chore: Increase print test coverage

- cmd/oras/internal/output/print.go
- internal/descriptor/descriptor.go
Move the logic of descriptor title vs media type to the descriptor package.
> refactor: Move descriptor logic to descriptor

- .gitignore
Ignore the e2e go sum file. Alternate to https://github.com/oras-project/oras/pull/1412
> chore: Ignore e2e test go sum file

- cmd/oras/internal/display/status/utils.go
- cmd/oras/root/pull.go
- internal/descriptor/descriptor.go
- internal/descriptor/descriptor_test.go
Move `GeneerateContentKey` to descriptor package and increase test coverage.
> refactor: Move generate content key method to descriptor

- cmd/oras/internal/display/content/manifest_fetch.go
- cmd/oras/internal/display/metadata/descriptor/manifest_fetch.go
- cmd/oras/internal/display/metadata/json/attach.go
- cmd/oras/internal/display/metadata/json/discover.go
- cmd/oras/internal/display/metadata/json/manifest_fetch.go
- cmd/oras/internal/display/metadata/json/pull.go
- cmd/oras/internal/display/metadata/json/push.go
- cmd/oras/internal/display/metadata/table/discover.go
- cmd/oras/internal/display/metadata/template/attach.go
- cmd/oras/internal/display/metadata/template/discover.go
- cmd/oras/internal/display/metadata/template/manifest_fetch.go
- cmd/oras/internal/display/metadata/template/pull.go
- cmd/oras/internal/display/metadata/template/push.go
- cmd/oras/internal/option/pretty.go
- cmd/oras/internal/output/json.go
- cmd/oras/internal/output/template.go
- cmd/oras/internal/output/template_test.go
Move the json and template output methods to the output package.
> refactor: Move two output functions to the output package

- .github/workflows/build.yml
Try reset the CLI version since the last success run was based on Codecov CLI v0.6.0 https://github.com/oras-project/oras/actions/runs/9590619238/job/26446251379
> build(ci): set codecov CLI version to avoid tokenless upload failure

- cmd/oras/internal/display/handler.go
- cmd/oras/internal/display/handler_test.go
- cmd/oras/internal/display/metadata/text/attach.go
- cmd/oras/internal/display/metadata/text/pull.go
- cmd/oras/internal/display/metadata/text/push.go
- cmd/oras/internal/display/metadata/text/push_test.go
- cmd/oras/internal/display/status/text.go
- cmd/oras/internal/output/print.go
- cmd/oras/internal/output/print_test.go
- cmd/oras/root/attach.go
- cmd/oras/root/pull.go
- cmd/oras/root/push.go
- cmd/oras/root/push_test.go
Pass printer object to text handler.
* Fewer arguments to the handlers
* Handlers use the same mutex used elsewhere
I'm going to explore the possibility of passing the printer to the json and template handler, but trying to keep this small.
> refactor: Pass printer to text handler

- cmd/oras/root/blob/delete.go
- cmd/oras/root/blob/push.go
- cmd/oras/root/cp.go
- cmd/oras/root/login.go
- cmd/oras/root/manifest/delete.go
- cmd/oras/root/manifest/push.go
- cmd/oras/root/repo/ls.go
- cmd/oras/root/repo/tags.go
- cmd/oras/root/resolve.go
- cmd/oras/root/version.go
Change the last calls to fmt.Fprint to use the printer object.
> refactor: Use printer object for output

- cmd/oras/internal/output/json_test.go
> chore: Add json test coverage

- cmd/oras/internal/option/common.go
- cmd/oras/root/attach.go
- cmd/oras/root/blob/delete.go
- cmd/oras/root/cp.go
- cmd/oras/root/login.go
- cmd/oras/root/manifest/delete.go
- cmd/oras/root/pull.go
- cmd/oras/root/push.go
- cmd/oras/root/repo/ls.go
- cmd/oras/root/repo/tags.go
- cmd/oras/root/resolve.go
- cmd/oras/root/tag.go
Follow up of #1426, de-duplicates `printer` initialization during command run(mentioned in https://github.com/oras-project/oras/pull/1426#pullrequestreview-2133693570)
> refactor: assembles printer in the common output option

- cmd/oras/internal/display/handler_test.go
- cmd/oras/internal/display/metadata/text/push_test.go
- cmd/oras/internal/option/common.go
- cmd/oras/internal/option/remote.go
- cmd/oras/internal/output/print.go
- cmd/oras/internal/output/print_test.go
- cmd/oras/root/blob/push.go
- cmd/oras/root/blob/push_test.go
- cmd/oras/root/cp_test.go
- cmd/oras/root/discover.go
- cmd/oras/root/manifest/push.go
- cmd/oras/root/version.go
Use the `cmd.ErrOrStderr()` for error output. This is more consistent and go scripting will be able to capture stderr.
This should be the final PR for the printer although it may be worth looking at where things are and to see what could be improved.
> refactor: Handle stderr similar to stdout

- cmd/oras/internal/option/remote.go
- cmd/oras/root/blob/push.go
- cmd/oras/root/discover.go
- cmd/oras/root/manifest/fetch.go
- cmd/oras/root/manifest/push.go
> refactor: reduce printer instantiation & unify stdout/stderr usage

- .github/workflows/build.yml
Use latest Codecov CLI as the tokenless upload issue is fixed in [v0.7.1](https://github.com/codecov/codecov-cli/releases/tag/v0.7.1), resolves #1423.
> build(ci): unset codecov CLI version

- cmd/oras/root/tag.go
- test/e2e/suite/command/tag.go
- disable oras tag fallback to tag schema when tagging a referrer
> fix: disable oras tag fallback to tag schema when tagging a referrer

- cmd/oras/internal/display/metadata/interface.go
- cmd/oras/internal/display/metadata/json/push.go
- cmd/oras/internal/display/metadata/template/push.go
- cmd/oras/internal/display/metadata/text/tag.go
- cmd/oras/internal/display/status/deprecated.go
- cmd/oras/root/tag.go
Create a tag handler for tagging
> refactor: Create tag handlers

- cmd/oras/internal/display/handler.go
- cmd/oras/internal/display/metadata/interface.go
- cmd/oras/internal/display/metadata/text/copy.go
- cmd/oras/internal/display/metadata/text/manifest_push.go
- cmd/oras/internal/display/metadata/text/tag.go
- cmd/oras/root/cp.go
- cmd/oras/root/manifest/push.go
- cmd/oras/root/tag.go
- internal/listener/tag.go
This PR unifies display handler usage by adding dedicated handlers to relevant commands, as a follow-up of #1438.
> refactor: add display handler for `cp`, `tag` and `manifest push`

- cmd/oras/internal/display/status/progress/manager.go
- cmd/oras/internal/display/status/track/target.go
Move these progress bar channel operations out of handler and into the manager.
> refactor: Move channel write logic to manager

- cmd/oras/internal/display/status/console/console.go
- cmd/oras/internal/display/status/progress/manager.go
- cmd/oras/internal/display/status/progress/manager_test.go
- cmd/oras/internal/display/status/progress/status_test.go
The variable name `len` conflicts with the built in. This will simplify my other PR a bit as well.
> fix: variable name conflicts with built in function

- cmd/oras/internal/display/status/progress/manager.go
- cmd/oras/internal/display/status/progress/messenger.go
- cmd/oras/internal/display/status/progress/messenger_test.go
- cmd/oras/internal/display/status/progress/status.go
- cmd/oras/internal/display/status/progress/status_test.go
- cmd/oras/internal/display/status/track/reader.go
Isolate details about the progress channel from users
> refactor: Isolate progress channel in Messenger

- cmd/oras/internal/display/handler.go
- cmd/oras/internal/display/status/interface.go
- cmd/oras/internal/display/status/text.go
- cmd/oras/internal/display/status/utils.go
- cmd/oras/root/cp.go
- cmd/oras/root/cp_test.go
This is a baby step to creating copy handlers for the cp command
> refactor: Create text copy handler

- cmd/oras/root/manifest/fetch.go
This PR adds an example for `--format` and it is a common task (for me at least) to get the digest.
> feature: Add manifest fetch documentation for digest

- cmd/oras/root/repo/tags.go
Fixes help documtation for `oras repo tags` command.
Closes: https://github.com/oras-project/oras/pull/1444
> fix: oras repo tags exlude-digest-tags documentation

- internal/graph/graph_test.go
- internal/testutils/fetcher.go
I wanted to get a feel for how people felt about making a mock fetcher as a test utility, so I created this small PR.
> refactor: Make mock fetcher generally available

- cmd/oras/internal/display/handler.go
- cmd/oras/internal/display/handler_test.go
- cmd/oras/internal/display/status/discard.go
- cmd/oras/internal/display/status/interface.go
- cmd/oras/internal/display/status/text.go
- cmd/oras/internal/display/status/text_test.go
- cmd/oras/internal/display/status/tty.go
- cmd/oras/internal/display/status/tty_console_test.go
- cmd/oras/internal/display/status/tty_test.go
- cmd/oras/internal/display/status/utils.go
- cmd/oras/internal/output/print.go
- cmd/oras/root/attach.go
- cmd/oras/root/attach_test.go
- cmd/oras/root/cp.go
- cmd/oras/root/push.go
- internal/descriptor/descriptor.go
- internal/graph/graph.go
- internal/graph/graph_test.go
- internal/testutils/fetcher.go
- internal/testutils/prompt.go
The PrintSuccessorStatus method was complicated with the function passed in and it didn't show the best separation of concerns. The print module ideally wouldn't know about a fetcher for example.
> refactor: Successor getting with separation of concerns

- cmd/oras/internal/display/status/text_test.go
- internal/testutils/error_fetcher.go
- internal/testutils/fetcher.go
The text_test was a little wordy and I though the error fetcher would be easier to find in its own file.
> refactor: DRY up text_test

- Makefile
Before this change, the nested $() in Makefile `$(GO_EXE) list ./... | grep -v internal/testutils | tr '\n' ','` generates empty return value so `-coverpkg` is actually set to `''`
> chore: reset test coverage package list

- internal/testutils/console.go
This build constraint on testutils/console is not needed. When I'm trying to debug a build issue on mac, I have to remove this.
> refactor: remove build constraint from testutils console

- cmd/oras/internal/option/target.go
- test/e2e/suite/command/pull.go
> fix: reference in the formatted output of `oras pull` is invalid

- cmd/oras/root/attach.go
- cmd/oras/root/discover.go
- cmd/oras/root/manifest/fetch.go
- cmd/oras/root/pull.go
- cmd/oras/root/push.go
> docs: add examples for --format

- cmd/oras/root/manifest/index/create.go
- test/e2e/internal/testdata/multi_arch/const.go
- test/e2e/suite/command/manifest_index.go
current output:
```
oras manifest index create myregistry.azurecr.io/test sha256:42c524c48e0672568dbd2842d3a0cb34a415347145ee9fe1c8abaf65e7455b46 --output - --pretty
Fetching sha256:42c524c48e0672568dbd2842d3a0cb34a415347145ee9fe1c8abaf65e7455b46
Fetched  sha256:42c524c48e0672568dbd2842d3a0cb34a415347145ee9fe1c8abaf65e7455b46
Packed   f16df862b7e3 application/vnd.oci.image.index.v1+json
Digest: sha256:f16df862b7e3d4f13c03d59655ed25a71a68e01e4aeec0d921d7310d6c67a360
{
"schemaVersion": 2,
"mediaType": "application/vnd.oci.image.index.v1+json",
"manifests": [
{
"mediaType": "application/vnd.oci.image.manifest.v1+json",
"digest": "sha256:42c524c48e0672568dbd2842d3a0cb34a415347145ee9fe1c8abaf65e7455b46",
"size": 1239,
"platform": {
"architecture": …
```
> feat: --output for `oras manifest index create`

- Makefile
Build the binary by default for the current OS and arch.
> feature: build binary for OS and arch by default

- cmd/oras/root/manifest/index/update.go
- test/e2e/internal/testdata/multi_arch/const.go
- test/e2e/suite/command/manifest_index.go
> feat: `--output` for oras manifest `index update`

- cmd/oras/root/push.go
Fix a couple minor warnings for the push command
> fix: Rename copy function to avoid built in collision

- cmd/oras/internal/display/status/console/console.go
- cmd/oras/internal/display/status/console/console_test.go
- cmd/oras/internal/display/status/progress/manager.go
- cmd/oras/internal/display/status/progress/manager_test.go
- internal/testutils/console.go
Create a interface for console so that alternate implementations can exist. In doing this, I found the `Size()` method was not properly implemented, so I created a `GetHeightWidth()` method.
Partial: https://github.com/oras-project/oras/issues/1461
> refactor: create an interface for status console

- cmd/oras/root/manifest/index/create.go
- cmd/oras/root/manifest/index/update.go
`oras manifest index update --add` now adds the original manifest descriptor, and which may include the annotations. The command should add the plain descriptor.
`oras manifest index update --merge` still adds the original manifest descriptors. The annotations may be meaningful under merge scenarios.
> fix: update --add should add plain descriptor

- cmd/oras/internal/option/platform.go
- cmd/oras/root/push.go
- test/e2e/internal/testdata/foobar/const.go
- test/e2e/suite/command/push.go
Add the platform option to the push command for example:
```
oras push --plain-http localhost:15000/oras:darwin,arm64  --artifact-platform darwin/arm64 --artifact-type 'application/vnd.oci.image.config.v1+json'  bin/darwin/arm64/oras:application/x-elf
```
Create the manifest for example:
```
oras manifest index create localhost:15000/oras:v1 sha256:ed3691788db69623790c46256dd11d8d6edc31be6e4762b53c74dfc3bb6792cf
```
The results
```
% oras manifest fetch --pretty localhost:15000/oras@sha256:c9e54542075ad502900d11b9b5d5bdb4b974ad580842515684d3fbb4849e2bb1
{
"schemaVersion": 2,
"mediaType": "application/vnd.oci.image.manifest.v1+json",
"artifactType": "application/vnd.oci.image.config.v1+json",
"config": {
"mediaType": …
```
> feat: add platform option to push command

- cmd/oras/internal/option/platform.go
Based on this comment https://github.com/oras-project/oras/pull/1500#discussion_r1803016606
> chore: remove unneeded parse method

- cmd/oras/root/push.go
- test/e2e/internal/testdata/foobar/const.go
- test/e2e/suite/command/push.go
Fix platform config type.
**Which issue(s) this PR fixes**
Fixes https://github.com/oras-project/oras/issues/1517
> fix: platform config type

- cmd/oras/internal/option/target.go
- cmd/oras/internal/option/target_test.go
- test/e2e/internal/utils/const.go
- test/e2e/suite/command/cp.go
The oci-layout can't be used when the image reference contains a slash ( see issue 1505). This PR introduces a new oci-layout-path that explicitly receives the path of the oci layout fixing the parsing ambiguity.
Fixes #1505
> feat(cmd/cp): add oci-layout-path flag

- test/e2e/suite/command/push.go
> chore: Add e2e test for platform push and pull

- test/e2e/scripts/prepare.sh
This PR adds a command to set golang binary path to ensure ginkgo always viable during e2e testing.
> chore(e2e): set go bin path

- docs/proposals/diagnose-experience.md
This proposal document aims to:
1. Identify the issues associated with the current implementation of the `--verbose` and `--debug` options.
2. Clarify the concepts of verbose output and debug logs.
3. List the guiding principles to write comprehensive, clear, and conducive verbose output and debug logs for effective diagnosis.
4. Propose solutions to improve the diagnostic experience for ORAS CLI users and developers.
5. Add examples for proposed changes (more examples will be appended).
Fixes #1091
> docs: Improve ORAS diagnose experience

- cmd/oras/internal/display/status/console/console_test.go
- internal/testutils/console.go
This PR fixes flaky console unit tests. To reproduce the flaky tests, try
```bash
go test -count=1000 -run ^TestConsole_Save$ oras.land/oras/cmd/oras/internal/display/status/console
```
PTY output might be interrupted by unexpected error like ` console_test.go:134: Save output error: failed to find "^[[?25l^[7^[[0m" in ""`
Fixes #1543
> fix(ut): fix flaky console tests

- cmd/oras/internal/display/handler.go
- cmd/oras/internal/display/handler_test.go
- cmd/oras/internal/display/status/interface.go
- cmd/oras/internal/display/status/text.go
- cmd/oras/internal/display/status/tty.go
- cmd/oras/internal/display/status/tty_console_test.go
- cmd/oras/root/cp.go
- cmd/oras/root/cp_test.go
Create tty copy handler with new `StartTracking` and `StopTracking` methods.
Partial: https://github.com/oras-project/oras/issues/1542
Closes: https://github.com/oras-project/oras/issues/1548
> refactor: create tty copy handler

- cmd/oras/root/attach.go
- cmd/oras/root/discover.go
- cmd/oras/root/manifest/fetch.go
- cmd/oras/root/pull.go
- cmd/oras/root/push.go
> docs: add experimental mark for examples

- .github/workflows/release-github.yml
- .goreleaser.yml
- README.md
- cmd/oras/root/attach.go
- cmd/oras/root/cp.go
- cmd/oras/root/discover.go
- cmd/oras/root/manifest/fetch.go
- cmd/oras/root/pull.go
- cmd/oras/root/push.go
- cmd/oras/root/repo/tags.go
- cmd/oras/root/tag.go
- test/e2e/suite/command/tag.go
This PR backports main-branch fixes into release-1.2 branch.
**This PR should be merged but not squashed.**
> chore: backport main-branch fixes into release-1.2 branch

- internal/version/version.go
This PR proposes to tag v1.2.1 based on a0228556766b6276010d8feb937af512e8a50808, commit changes to branch release-1.2 and release. At least 3 approvals are needed from the 5 owners.
Below is a summary of change notes since [v1.2.0](https://github.com/oras-project/oras/releases/tag/v1.2.0):
- Fix https://github.com/oras-project/oras/issues/1436: `oras tag` no longer creates referrer tag.
- Bump Golang to 1.23.4
- Update dependencies
- Enhance document
* bump: golang version to fix CVE-2024-24790 and CVE-2024-34156 by @qweeah in https://github.com/oras-project/oras/pull/1562
* chore: bump golang and dependencies by @qweeah in https://github.com/oras-project/oras/pull/1564
* chore: backport main-branch fixes into release-1.2 branch by @qweeah in …
> bump: tag and release ORAS CLI v1.2.1

- internal/version/version.go
This PR proposes to tag v1.3.0-beta.1 based on 2ca02f6f6514200366df26ba9ef6d1b311629dad and release. At least 3 approvals are needed from the 5 owners.
Below is a summary of change notes since [v1.2.0](https://github.com/oras-project/oras/releases/tag/v1.2.0):
- Add OS and architecture information into `oras version`
- Add multi-arch artifacts support
- Introduce `oras manifest index create` to craft OCI index manifests
- Introduce `oras manifest index update` to update existing OCI index manifests
- Introduce `--artifact-platform` option for `oras push` to push multi-arch artifacts
- Introduce `--oci-layout-path` option for `oras cp` to copy via full reference in OCI Image Layout
- `-v`, `--verbose` flag is deprecated and all status text output …
> bump: tag and release ORAS CLI v1.3.0-beta.1

- cmd/oras/internal/display/content/manifest_fetch.go
- cmd/oras/internal/display/content/manifest_index.go
- cmd/oras/root/pull.go
> fix: handle errors returned by `Close()` in write paths

- cmd/oras/internal/display/metadata/interface.go
- cmd/oras/internal/display/metadata/json/push.go
- cmd/oras/internal/display/metadata/template/push.go
- cmd/oras/internal/display/metadata/text/push.go
- cmd/oras/internal/display/metadata/text/push_test.go
- cmd/oras/root/push.go
> refactor: apply metadata render interface to oras push command

- internal/version/version.go
This PR proposes to tag `v1.2.2` based on 677529b4e7c38e3295e0883a2ee8a536e3a860f4, commit changes to branch `release-1.2` and release. At least 3 approvals are needed from the 5 owners.
Below is a summary of change notes since [v1.2.1](https://github.com/oras-project/oras/releases/tag/v1.2.1):
- Minor security enhancements: address [CVE-2024-45337](https://github.com/advisories/GHSA-v778-237x-gjrc)
>[!NOTE]
> The `oras` CLI is not impacted by CVE-2024-45337 since `oras` is a client tool.
* build(deps): bump golang.org/x/crypto from 0.26.0 to 0.31.0 by @Wwwsylvia in https://github.com/oras-project/oras/pull/1591
**Full Changelog**: https://github.com/oras-project/oras/compare/v1.2.1...677529b4e7c38e3295e0883a2ee8a536e3a860f4
> bump: tag and release ORAS CLI v1.2.2

- CODEOWNERS
- MAINTAINERS.md
Nominate Sylvia Lei (@Wwwsylvia) as a maintainer of the `oras` repository.
Sylvia has contributed and merged `5` PRs and reviewed `19` PRs during the last half a year (180 days). Since Sylvia is the major maintainer of the `oras-go` repository, she will address the issues in the CLI in a quicker way and reflect in the `oras-go` development holistically.
> docs: add Sylvia Lei as a maintainer

- cmd/oras/internal/option/target.go
marked --oci-layout-path as experimental
Fixes #1582
> fix: mark `--oci-layout-path` as experimental

- .github/licenserc.yml
I would like to add SVG file to license checker ignoring list since this is graphic files instead of code. There is not necessary to add license check to SVG files.
Fixes https://github.com/oras-project/oras/issues/1619
> chore: add SVG file to license checker ignoring list

- go.mod
- go.sum
Bump the `oras-go` dependency to the latest commit [`cb6d75be7dd4a78f25fe9d00c76c0d15c4296da6`](https://github.com/oras-project/oras-go/commit/cb6d75be7dd4a78f25fe9d00c76c0d15c4296da6) which includes the bug fix for https://github.com/oras-project/oras-go/issues/865.
Fixes #1593
> fix: bump `oras-go` to the latest commit which fixes the symlink issue

- cmd/oras/internal/display/handler.go
- cmd/oras/internal/display/metadata/interface.go
- cmd/oras/internal/display/metadata/text/resolve.go
- cmd/oras/root/resolve.go
> refactor: add resolve metadata handler

- cmd/oras/internal/option/applier.go
- cmd/oras/internal/option/parser.go
Refactor code for better readability, leveraging the new `iter` package.
> refactor: use iter for cleaner code

- cmd/oras/main.go
**What this PR does / why we need it**: So the `defer cancel()` runs. Go won't run defers if `os.Exit()` is called, so in the case of an error the context cancelation will not run. See https://go.dev/play/p/0AIokfnVk0m for an example. Probably not a big deal, but something I noticed poking around the source code while exploring oras and thought I would send this small PR.
> refactor: split a run and main function so defers Execute

- cmd/oras/internal/option/verbose.go
- cmd/oras/root/blob/delete.go
- cmd/oras/root/blob/fetch.go
- cmd/oras/root/login.go
- cmd/oras/root/manifest/delete.go
- cmd/oras/root/manifest/fetch.go
- cmd/oras/root/manifest/fetch_config.go
- cmd/oras/root/repo/ls.go
- cmd/oras/root/repo/tags.go
- cmd/oras/root/resolve.go
- cmd/oras/root/tag.go
- test/e2e/suite/auth/auth.go
- test/e2e/suite/command/blob.go
- test/e2e/suite/command/manifest.go
- test/e2e/suite/command/repo.go
- test/e2e/suite/command/resolve.go
- test/e2e/suite/command/tag.go
This PR brings back the `--verbose` flag to the following commands and mark it as deprecated.
oras blob delete
oras blob fetch
oras login
oras manifest delete
oras manifest fetch
oras manifest fetch-config
oras repo ls
oras repo tags
oras resolve
oras tag
Fixes #1640 
> fix: bring back `--verbose` flag

- docs/proposals/formatted-output.md
This PR improves formatted output for `oras discover`. For example, if the referrers have associated referrers, ORAS should enable users to show the manifest content of the subject image and all referrers in multiple formats. 
Fixes #1403
> docs: improve formatted output for oras discover

- go.mod
- go.sum
Upgrade go crypto module to fix CVE-2025-22869
> build(deps): upgrade go crypto module to v0.36.0

- cmd/oras/internal/option/cache_test.go
Use test environment for cache test for lint and reliability.
> fix: use test Setenv during tests

- cmd/oras/internal/option/confirmation_test.go
- cmd/oras/internal/option/descriptor_test.go
- cmd/oras/internal/option/platform_test.go
These embedded members fail staticcheck for newest lint because the embedded member cannot be extracted. This PR is for tests only. There is another PR for non-tests.
> fix: staticcheck fails for embedded member

- cmd/oras/internal/display/status/console/console.go
- cmd/oras/root/discover.go
- cmd/oras/root/login.go
- cmd/oras/root/push.go
- cmd/oras/root/repo/ls.go
Newer lint fails on these embedded struct members reference.
> fix: staticcheck lint failures of embedded member

- cmd/oras/root/manifest/index/create.go
1.   Changing <name> to <target> explicitly states where the manifest index will be created.
2.   Keeping all positional arguments first improves readability and reduces the risk of users mistaking flags like --oci-layout as having their own positional arguments.
Fixes: #1638
Fixes #
> docs: update the help doc for `oras manifest index create`

- go.mod
- go.sum
- test/e2e/suite/command/push.go
1. Bump `oras-go` to the latest commit [`f7a6126986d97f498be7b516ebf5478a49a6df86`](https://github.com/oras-project/oras-go/commit/f7a6126986d97f498be7b516ebf5478a49a6df86)
2. Fix an E2E test cases that used an invalid media type
Fixes #1659, fixes #1694, fixes #1695
> build(deps): bump oras-go to the latest commit which fixes the "compare and swap" error

- internal/version/version.go
This PR proposes tagging and releasing `v1.2.3` based on commit 10fb4e54ba99e8df2ec29a0f14eb12e4058bb500. Approval from at least 4 of the 6 owners listed below is required:
Changelog: https://github.com/oras-project/oras/compare/v1.2.2...10fb4e54ba99e8df2ec29a0f14eb12e4058bb500
---
* Fix #1599: Auth token scope not correctly added when using --debug or --no-tty with oras push
* Fix #1623: Should show KB instead of kB in the progress bar
* Minor security enhancements
> bump: tag and release ORAS CLI v1.2.3

- cmd/oras/internal/display/metadata/text/attach.go
- cmd/oras/internal/display/metadata/text/blob_delete.go
- cmd/oras/internal/display/metadata/text/blob_push.go
- cmd/oras/internal/display/metadata/text/copy.go
- cmd/oras/internal/display/metadata/text/manifest_delete.go
- cmd/oras/internal/display/metadata/text/manifest_push.go
- cmd/oras/internal/display/metadata/text/pull.go
- cmd/oras/internal/display/metadata/text/push.go
- cmd/oras/internal/option/target.go
- cmd/oras/root/manifest/index/create.go
Every time I see this method, I wonder what it does. This name makes it clear.
> refactor: rename Target AnnotatedReference method

- cmd/oras/root/discover.go
`-v` has been deprecated for `oras discover` and there should not be related examples anymore
Fixes #
> fix(docs): remove a discover example with -v

- cmd/oras/internal/display/metadata/tree/discover_test.go
Ignoring two test defer calls for lint
> fix(lint): ignore returns from test defer calls

- cmd/oras/internal/display/status/tty_console_test.go
Rename variable called slave with the name child
> fix: replace slave var for child

- cmd/oras/root/cp_test.go
These tests don't work on mac, so running here, but just renaming slave to child
> fix: rename slave to child for cp test

- docs/proposals/backup-restore.md
Specification for the way the `oras backup` and `oras restore` commands will work.
**Which issue(s) this PR fixes**:
Partial: https://github.com/oras-project/oras/issues/1366
> docs: backup and restore specification

- docs/proposals/formatted-output.md
This PR adds documentation for the output formats for `oras repo ls` and `oras repo tags` commands.
Related to #1547 
Related to #1758 
> docs(spec): define output formats for oras repo commands

- cmd/oras/internal/display/status/console/console_test.go
- cmd/oras/internal/display/status/track/target_test.go
- cmd/oras/internal/display/status/tty_console_test.go
- cmd/oras/internal/option/terminal_test.go
- cmd/oras/root/blob/fetch_test.go
- cmd/oras/root/blob/push_test.go
- cmd/oras/root/cp_test.go
- internal/testutils/console.go
Exclude operating systems that are broken for these tests rather include operating systems we do not technically support
> test: exclude incompatible test Go OSes

- cmd/oras/internal/option/binary_target.go
- cmd/oras/internal/option/remote.go
- cmd/oras/internal/option/spec.go
- cmd/oras/internal/option/target.go
- cmd/oras/internal/option/target_test.go
It kind of looks like this Target/Remote code was in the middle of some refactor that was never completed. This doesn't address all the issues, but it does clean up flag/prefix/description handling a bit.
> refactor: ApplyFlags with prefix for Remote and Target

- cmd/oras/root/pull.go
- test/e2e/suite/command/pull.go
This PR removes the `[Preview]` label on the `include-subject` flag for the `oras pull` command. This means to promote this flag from preview level to stable.
Fixes #1811
> chore: remove [Preview] label on `--include-subject` for `oras pull`

- internal/version/version.go
This PR proposes tagging and releasing `v1.3.0-rc.1` based on commit 39748a41ba2fede9788f018cfb0fcb951093adf5. Approval from at least 4 of the 6 owners listed below is required:
Changelog: https://github.com/oras-project/oras/compare/v1.3.0-beta.4...39748a41ba2fede9788f018cfb0fcb951093adf5
---
* Promote the following commands and flags from `Preview` to `Stable`:
* `oras attach`
* `oras attach --platform`
* `oras pull --include-subject`
* Promote `oras resolve` from `Experimental` to `Preview`
* Fix #1795, #1825: redundant blank lines in terminal output
* Upgrade to Go `1.25.0`
* Update dependencies
* bump: tag and release ORAS CLI v1.3.0-beta.4 by @Wwwsylvia in …
> bump: tag and release ORAS CLI v1.3.0-rc.1

- cmd/oras/internal/display/metadata/tree/discover.go
This PR updates the colors of digests and the `[annotation]` nodes in the `oras discover` tree view to improve readability.
**BEFORE**:
**AFTER**:
Fixes #1772 
> chore(ux): update colors for oras discover tree view

- cmd/oras/root/backup.go
- test/e2e/suite/command/backup.go
This PR improves the error message in `oras backup` for the case where the output path ends with `.tar` but is an existing directory.
**BEFORE**:
> Error: unable to create output file test.tar: open test.tar: is a directory
**AFTER**:
> Error: the output path test.tar already exists and is a directory: open test.tar: is a directory
> To back up to a tar archive, please specify a different output file name or remove the existing directory.
Fixes #1831
> chore(ux): improve oras backup error message

- internal/version/version.go
This PR proposes tagging and releasing `v1.3.0-rc.2` based on commit 99b6e1ec698937a5b7e0984e747c7c61c6f2cbdd. Approval from at least 4 of the 6 owners listed below is required:
Changelog: https://github.com/oras-project/oras/compare/v1.3.0-rc.1...99b6e1ec698937a5b7e0984e747c7c61c6f2cbdd
---
* Refine the color scheme for the tree view in `oras discover` for better visual clarity
* Improve the error message for `oras backup` when the output file exists as a directory
* bump: tag and release ORAS CLI v1.3.0-rc.1 by @Wwwsylvia in https://github.com/oras-project/oras/pull/1830
* chore(ux): update colors for oras discover tree view by @Wwwsylvia in …
> bump: tag and release ORAS CLI v1.3.0-rc.2
