.gitignore, README.md, examples/simple_push_pull.go
=> example of how to use as module

pkg/oras/store.go
=> make MemoryStore thread-safe

cmd/oras/pull.go, pkg/content/content_test.go, pkg/content/errors.go, pkg/content/file.go
Give security options to prevent
- File overwritting
- [Directory traversal attack](https://en.wikipedia.org/wiki/Directory_traversal_attack)
By default, those security options are selected.
Resolve #32
=> Enhance security on FileStore

Dockerfile, Makefile, README.md, cmd/oras/pull.go, cmd/oras/push.go, examples/simple_push_pull.go, pkg/oras/oras_test.go, pkg/oras/pull.go, pkg/oras/store.go
Replace `shizhMSFT` with `deislabs`.
Resolve #39
=> Update package references

README.md
Added intro context
Removed Build Badge until we get Codefresh reconfigured
=> Prep for public access

pkg/oras/push.go
=> Bug Fix: Config Annotations should not be reset

pkg/oras/push.go, pkg/oras/push_opts.go
=> Option to change config media type

docs/README.md, docs/annotations.md, docs/config.md, docs/store.md
Resolves #59 .
This docuementation includes the changes made by #93 #95 .
=> Documentations

README.md
=> Add info on ORAS community

README.md, implementors.md
Signed-off-by: Steven Lasker <stevenlasker@hotmail.com>
=> ORAS Readme Updates

README.md
@jdolitsky @SteveLasker 
Fixes issue https://github.com/deislabs/oras/issues/143
One line change in the README for accuracy.
=> oras-143 updating mediaType in example in README

implementors.md
Adds a reference to ECR support and the blog post.
Closes #105;
=> docs: add ECR docs

cmd/oras/discover.go
=> Pretty Print `oras discover`

README.md
This change adds simple documentation for the cache functionality added in https://github.com/deislabs/oras/pull/203
=> Add documentation for cache usage

cmd/oras/push.go
Make the default config media type consistent with the oras library.
=> consistent default config media type

MAINTAINERS, OWNERS, README.md
Also, rename MAINTAINERS to OWNERS
cc @jzelinskie @vbatts
=> Add jzelinskie and vbatts to emeritus

LICENSE
Actioning as part of CNCF onboarding
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
=> Update LICENSE to Apache v2

.goreleaser.yml
=> Add support for pre-release

go.mod, go.sum
=> Updated oras-project/containerd with artifact filtering

.goreleaser.yml
=> release zip for windows

cmd/oras/cache.go, cmd/oras/login.go, go.mod, go.sum
- Removed `require` stanza
- Drop direct dependencies on `github.com/docker/docker` and `github.com/pkg/errors`
=> Clean up dependency

cmd/oras/internal/option/remote.go
=> Use caching for auth client

internal/version/version.go
Signed-off-by: Billy Zha <qweeah@gmail.com>
=> Prepare for v0.13.0

Makefile
Related to #416
Signed-off-by: Billy Zha <qweeah@gmail.com>
=> Update artifact tarball names in makefile

cmd/oras/push.go, internal/version/version.go
Resolves #379 
Signed-off-by: Billy Zha <qweeah@gmail.com>
=> Merging `artifacts` Branch: Add exporting manifest option for push

go.mod, go.sum
=> Fix retagging failure with updated oras-go

go.mod, go.sum
=> Fix push error for ECR

cmd/oras/attach.go, cmd/oras/copy.go, cmd/oras/discover.go, cmd/oras/internal/errors/errors.go, cmd/oras/pull.go, go.mod, go.sum
And also update oras-go to rc2
=> refactor: move error to cmd internal packages

cmd/oras/internal/option/remote.go
=> fix: enable proxy in auth

cmd/oras/discover.go
=> doc: fix typo in long description

internal/version/version.go
=> bump: update version to release 0.14.0

cmd/oras/push.go
rename the --manifest-config to --config for push command
=> fix!: rename the --manifest-config to --config for push command

cmd/oras/copy.go, cmd/oras/push.go
=> doc: update example doc

go.mod, go.sum, internal/version/version.go
=> bump: upgrade oras-go

internal/cache/target.go
=> fix: handle push error for internal cache

cmd/oras/internal/option/remote.go, cmd/oras/internal/option/remote_test.go, cmd/oras/login.go, cmd/oras/logout.go, internal/credential/store.go
=> fix: provide function to support hostname mapping

cmd/oras/attach.go
=> fix: correct help doc description for attach

cmd/oras/internal/display/print.go, cmd/oras/pull.go
=> fix: missing status for pull

cmd/oras/repository/cmd.go, cmd/oras/repository/list.go
=> feat: Make `repo` alias to `repository`

cmd/oras/attach.go, cmd/oras/discover.go, cmd/oras/pull.go, cmd/oras/push.go, cmd/oras/repository/list.go, cmd/oras/repository/show-tags.go
=> doc: make flags before arguments in examples

cmd/oras/repository/show-tags.go
=> feat: alias `show-tags=tags` for `oras repository`

cmd/oras/attach.go
=> fix: make attach required via cobra

cmd/oras/internal/option/platform.go
=> fix: update argument description for platform

go.mod, go.sum
=> build: bump oras-go version

cmd/oras/internal/option/platform.go, cmd/oras/push.go
Signed-off-by: Jun <wju@microsoft.com>
=> feat: support tagging multiple tags at once for oras push

cmd/oras/pull.go
=> fix: reorder status logs for `oras pull`

cmd/oras/copy.go, cmd/oras/manifest/push.go, cmd/oras/push.go
Resolves: #355 
Signed-off-by: Jun <wju@microsoft.com>
=> feat: support tagging multiple tags at once for oras copy

internal/version/version.go
=> bump: update version to 0.15.0

cmd/oras/attach.go
=> feat: support concurrency tuning for oras attach

cmd/oras/logout.go
=> fix: logout specified credential config file if provided

cmd/oras/attach.go
=> fix: annotates manifest for attach command

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/license-checker.yml, cmd/oras/attach.go, cmd/oras/logout.go, cmd/oras/manifest/fetch.go, cmd/oras/manifest/push.go
=> fix: patch bug fixes to release-0.15

internal/version/version.go
=> bump: update version for 0.15 release

cmd/oras/discover.go
=> fix: use optional plural form

cmd/oras/discover.go
=> feat: support discovering with platform selection

cmd/oras/manifest/fetch_config.go
=> feat: add alias for fetch-config

internal/version/version.go
=> bump: release 0.16

internal/trace/transport.go
=> feat: add directional hints for debug logs

cmd/oras/pull.go, cmd/oras/repository/tags.go, cmd/oras/tag/tag.go
Related to https://github.com/oras-project/oras/issues/378
=> feat(oci-layout): support `oras tag`,`oras repo tags` and `oras pull`

cmd/oras/manifest/delete.go
=> feat: add distribution flag to `manifest delete`

internal/version/version.go
Signed-off-by: Sylvia Lei <lixlei@microsoft.com>
=> bump: release v1.0.0-rc.1

cmd/oras/internal/option/remote.go, cmd/oras/internal/option/remote_test.go
If implemented the assembled `oras auth client` will have the default retry policy set for the underlying http roundTripper.
**Which issue(s) this PR fixes**:
Fixes #769 
=> feat: add retry support to the auth client

cmd/oras/push.go, test/e2e/suite/command/push.go
This PR fixes a bug in oras push.
Fixes #849 
=> fix: push bug when multi tagging

internal/version/version.go
This PR prepares release for 1.0.0-rc.2
=> bump: update version to rc.2

test/e2e/internal/testdata/multi_arch/const.go, test/e2e/internal/utils/flags.go, test/e2e/suite/command/blob.go, test/e2e/suite/command/cp.go, test/e2e/suite/command/pull.go
This PR adds e2e test specs. 
Fixes #868 
=> test(e2e): add OCI layout e2e specs for `oras cp`

test/e2e/internal/utils/exec.go, test/e2e/internal/utils/match/keywords.go, test/e2e/internal/utils/match/request.go, test/e2e/suite/command/custom_header.go
Part of #809 (add e2e tests except for cp)
=> test: add e2e tests for custom header feature

test/e2e/suite/command/repo.go
This PR adds e2e specs for `oras repo tags` with OCI layout support.
Fixes #872 
=> test(e2e): OCI layout specs for `oras repo tags`

test/e2e/internal/testdata/foobar/const.go, test/e2e/suite/command/manifest.go, test/e2e/suite/command/push.go
This PR adds e2e test specs for `oras copy` and refactor some existent specs.
Fixes #877 
=> test(e2e): OCI layout e2e specs for `oras push`

test/e2e/suite/command/manifest.go
=> test: add e2e specs for manifest fetch under oci-layout

Makefile
This reverts commit d310eb685f8f9249a354139fa7d44be467e8fdc1.
Accidental push to main
Fixes #
=> Revert "Add help to make file"

go.mod, go.sum
=> build(deps): bump github.com/oras-project/oras-credentials-go from 0.1.1 to 0.2.0

test/e2e/internal/testdata/multi_arch/const.go, test/e2e/suite/command/attach.go, test/e2e/suite/command/manifest.go
=> test(e2e): update spec-related constants to string literal

.github/workflows/release-github.yml, Dockerfile, internal/version/version.go
This PR reverts commit 42650e5778283be7e4926f123f183db12dfbacaa.
=> revert: "chore: update minor version (#1000)"

internal/version/version.go
This reverts commit edfc253f8cc1bb71471158a55fb71fd7f723c846.
=> revert: "bump: update oras version to 1.1.0-rc.1"

cmd/oras/internal/option/packer.go
=> chore(ux): improve error message for bad annotation format

cmd/oras/internal/option/packer.go
=> chore: improve error message if the provided annotation file is invalid

.github/.codecov.yml
Resets patch coverage check to 80%
=> chore(ci): update patch coverage check to 80%

.github/workflows/build.yml
Update codecov Github Action to v4.
Fixes #1291 
=> bump(ci): update codecov gha to v4

internal/version/version.go
This PR proposes to tag v1.2.0-rc.1 based on https://github.com/oras-project/oras/commit/ed8d791300647bf5c5e4325af4e4280227640387 and release. At least 3 approvals are needed from the 5 owners.
Below is a summary of change notes since [v1.2.0-beta.1](https://github.com/oras-project/oras/releases/tag/v1.2.0-beta.1):
- x509 mTLS authentication with OCI registries: https://github.com/oras-project/oras/issues/491
- new token auth experience via `--identity-token`: https://github.com/oras-project/oras/issues/742
- Better multi-arch image attaching experience: allow adding referrer artifact to a specific sub-platform: https://github.com/oras-project/oras/issues/813
- **BREAKING CHANGE** `oras discover` by default shows tree view output
- Apply `--format` …
=> bump: tag and release ORAS CLI v1.2.0-rc.1

cmd/oras/root/tag.go
=> fix(doc): resolve example error for `oras tag`

cmd/oras/root/cp_test.go
=> fix: Minor spelling error in test

cmd/oras/internal/display/metadata/text/push_test.go, cmd/oras/internal/output/print.go, cmd/oras/internal/output/print_test.go
I'm not a big fan of the print error, but other things I am a lot more concerned with.
=> chore: Bring back the print error

internal/descriptor/descriptor_test.go
Minor fixes to the descriptor test.
=> fix: A couple small fixes to the descriptor test

cmd/oras/internal/display/status/text_test.go, cmd/oras/internal/option/remote_test.go, cmd/oras/internal/output/print_test.go
It looks like a new version of lint has some new complaints. This should fix them
=> chore: lint fixes for new lint

cmd/oras/root/cp.go
=> docs: improve the description of cp

cmd/oras/root/version.go, test/e2e/suite/command/version.go, test/e2e/suite/command/version_darwin.go, test/e2e/suite/command/version_linux.go
=> feat: add OS/Arch information into oras version

cmd/oras/root/attach.go, cmd/oras/root/discover.go, cmd/oras/root/manifest/fetch.go, cmd/oras/root/pull.go, cmd/oras/root/push.go
This PR adds experimental marks to examples.
=> docs: add experimental marks to examples

cmd/oras/root/push.go
#1600 (authored by @hopegi) was merged into `release-1.2` and should be ported to the main branch
Fixes #1599
=> fix: scope action only has pull when get service token in executing cmd org push

cmd/oras/internal/display/metadata/interface.go, cmd/oras/internal/display/metadata/json/discover.go, cmd/oras/internal/display/metadata/table/discover.go, cmd/oras/internal/display/metadata/template/discover.go, cmd/oras/internal/display/metadata/tree/discover.go, cmd/oras/root/discover.go
=> refactor: apply metadata render interface to oras discover command

docs/proposals/proposal-doc-template.md
I am proposing an enhancement proposal doc template to frame the content and make sure necessary background/scenarios of each proposal are included. It will be easier for reviewers to understand the proposal and provide feedback.
This is a common practice that a few mature communities like Kubernetes are applying https://github.com/kubernetes/enhancements/blob/master/keps/README.md
=> docs: add an enhancement proposal doc template

cmd/oras/internal/display/handler.go, cmd/oras/internal/display/metadata/interface.go, cmd/oras/internal/display/metadata/text/blob_delete.go, cmd/oras/root/blob/delete.go
=> refactor: add blob delete metadata handler

cmd/oras/internal/display/handler.go, cmd/oras/internal/display/metadata/interface.go, cmd/oras/internal/display/metadata/text/manifest_delete.go, cmd/oras/root/manifest/delete.go
=> refactor: add manifest delete metadata handler

README.md
Adds the goreportcard to README
=> docs: add goreportcard to README

cmd/oras/internal/option/target.go
=> fix: target NewReadonlyTarget comment

cmd/oras/internal/option/target.go
Every time I'm in this file, I get confused about what opts is because that is used outside this everywhere for options
=> fix: Change receiver name for target

cmd/oras/root/manifest/index/create.go
This error check will always be false.
=> fix: unneeded error check

internal/version/version.go
This PR proposes tagging and releasing `v1.3.0-beta.3` based on commit fce0546a012909e4d7234677f92a85b482030e39. Approval from at least 4 of the 6 owners listed below is required:
Changelog: https://github.com/oras-project/oras/compare/v1.3.0-beta.2...fce0546a012909e4d7234677f92a85b482030e39
---
* Add `oras manifest get` as an alias for `oras manifest fetch`.
* Refactor the output of `oras discover`:
* **BREAKING CHANGE**: Field `manifests` is now `referrers`.
* Include information of the subject manifest in the output using the `--format json` option.
* Display indirect referrers for all formats of `oras discover`
* **BREAKING CHANGE**: Show all levels of referrers for `go-template` …
=> bump: tag and release ORAS CLI v1.3.0-beta.3

Dockerfile
Update alpine version to the latest
=> build: use alpine 3.21.3

cmd/oras/internal/display/metadata/table/discover.go, cmd/oras/internal/display/metadata/table/discover_test.go
Test coverage for the discover handler.
=> Add test coverage for discover handler

cmd/oras/internal/display/metadata/model/discover.go, test/e2e/suite/command/discover.go
=> fix: discover json format should show referrers field when no referrer is found

cmd/oras/root/manifest/index/create.go, cmd/oras/root/manifest/index/create_test.go, cmd/oras/root/manifest/index/update.go, test/e2e/suite/command/manifest_index.go
This implements the new behavior proposed in https://github.com/oras-project/oras/pull/1696.
I am contributing this change on behalf of the [OpenTofu](https://opentofu.org/) project.
**Which issue(s) this PR fixes**:
Fixes #1670
=> feat: oras manifest index: artifactType for index and child manifest descriptors

docs/proposals/backup-restore.md
@sajayantony and @shizhMSFT suggested using a single OCI layout for the directory structure of the backup. It seems to work well in my basic backup/restore PR https://github.com/oras-project/oras/pull/1769
=> docs: backup and restore to single OCI layout

internal/version/version.go
This PR proposes tagging and releasing `v1.3.0-beta.4` based on commit 582ae373493985fb8cda60a4306b52d4e9f70b8e. Approval from at least 4 of the 6 owners listed below is required:
Changelog: https://github.com/oras-project/oras/compare/v1.3.0-beta.3...582ae373493985fb8cda60a4306b52d4e9f70b8e
---
* **Backup and Restore Commands**: 
* **`oras backup`**: New command to back up artifacts from registries to local OCI layout directories or tar archives, with support for including referrers via the `--include-referrers` flag
* **`oras restore`**: New command to restore artifacts from local OCI layout directories or tar archives back to registries, with dry-run mode support via the …
=> bump: tag and release ORAS CLI v1.3.0-beta.4

cmd/oras/root/attach.go
=> chore: mark `--platform` flag of `oras attach` from preview to stable

internal/version/version.go
This PR proposes tagging and releasing `v1.3.0` based on commit 40530fe4c68e5825b868cd874bd46fc0cdd0f432. Approval from at least 4 of the 6 owners listed below is required:
Changelog since `v1.2.3`: https://github.com/oras-project/oras/compare/v1.2.3...40530fe4c68e5825b868cd874bd46fc0cdd0f432
Changelog since `v1.3.0-rc.2`: https://github.com/oras-project/oras/compare/v1.3.0-rc.2...40530fe4c68e5825b868cd874bd46fc0cdd0f432
---
* Promote the following commands and flags from `Preview` to `Stable`:
* `oras attach`
* `oras attach --platform`
* `oras pull --include-subject`
* Promote `oras resolve` from `Experimental` to `Preview`
* Comply with OCI [distribution-spec …
=> bump: tag and release ORAS CLI v1.3.0
